// Code generated by ent, DO NOT EDIT.

package groupaccessgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGroupID, v))
}

// GranteeUserID applies equality check predicate on the "grantee_user_id" field. It's identical to GranteeUserIDEQ.
func GranteeUserID(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGranteeUserID, v))
}

// GranteeRoleID applies equality check predicate on the "grantee_role_id" field. It's identical to GranteeRoleIDEQ.
func GranteeRoleID(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGranteeRoleID, v))
}

// AccessLevel applies equality check predicate on the "access_level" field. It's identical to AccessLevelEQ.
func AccessLevel(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldAccessLevel, v))
}

// GrantedByUserID applies equality check predicate on the "granted_by_user_id" field. It's identical to GrantedByUserIDEQ.
func GrantedByUserID(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedByServicePrincipalID applies equality check predicate on the "granted_by_service_principal_id" field. It's identical to GrantedByServicePrincipalIDEQ.
func GrantedByServicePrincipalID(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGrantedByServicePrincipalID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldGroupID, vs...))
}

// GranteeUserIDEQ applies the EQ predicate on the "grantee_user_id" field.
func GranteeUserIDEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGranteeUserID, v))
}

// GranteeUserIDNEQ applies the NEQ predicate on the "grantee_user_id" field.
func GranteeUserIDNEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldGranteeUserID, v))
}

// GranteeUserIDIn applies the In predicate on the "grantee_user_id" field.
func GranteeUserIDIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldGranteeUserID, vs...))
}

// GranteeUserIDNotIn applies the NotIn predicate on the "grantee_user_id" field.
func GranteeUserIDNotIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldGranteeUserID, vs...))
}

// GranteeUserIDIsNil applies the IsNil predicate on the "grantee_user_id" field.
func GranteeUserIDIsNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIsNull(FieldGranteeUserID))
}

// GranteeUserIDNotNil applies the NotNil predicate on the "grantee_user_id" field.
func GranteeUserIDNotNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotNull(FieldGranteeUserID))
}

// GranteeRoleIDEQ applies the EQ predicate on the "grantee_role_id" field.
func GranteeRoleIDEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGranteeRoleID, v))
}

// GranteeRoleIDNEQ applies the NEQ predicate on the "grantee_role_id" field.
func GranteeRoleIDNEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldGranteeRoleID, v))
}

// GranteeRoleIDIn applies the In predicate on the "grantee_role_id" field.
func GranteeRoleIDIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldGranteeRoleID, vs...))
}

// GranteeRoleIDNotIn applies the NotIn predicate on the "grantee_role_id" field.
func GranteeRoleIDNotIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldGranteeRoleID, vs...))
}

// GranteeRoleIDIsNil applies the IsNil predicate on the "grantee_role_id" field.
func GranteeRoleIDIsNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIsNull(FieldGranteeRoleID))
}

// GranteeRoleIDNotNil applies the NotNil predicate on the "grantee_role_id" field.
func GranteeRoleIDNotNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotNull(FieldGranteeRoleID))
}

// AccessLevelEQ applies the EQ predicate on the "access_level" field.
func AccessLevelEQ(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldAccessLevel, v))
}

// AccessLevelNEQ applies the NEQ predicate on the "access_level" field.
func AccessLevelNEQ(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldAccessLevel, v))
}

// AccessLevelIn applies the In predicate on the "access_level" field.
func AccessLevelIn(vs ...string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldAccessLevel, vs...))
}

// AccessLevelNotIn applies the NotIn predicate on the "access_level" field.
func AccessLevelNotIn(vs ...string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldAccessLevel, vs...))
}

// AccessLevelGT applies the GT predicate on the "access_level" field.
func AccessLevelGT(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGT(FieldAccessLevel, v))
}

// AccessLevelGTE applies the GTE predicate on the "access_level" field.
func AccessLevelGTE(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGTE(FieldAccessLevel, v))
}

// AccessLevelLT applies the LT predicate on the "access_level" field.
func AccessLevelLT(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLT(FieldAccessLevel, v))
}

// AccessLevelLTE applies the LTE predicate on the "access_level" field.
func AccessLevelLTE(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLTE(FieldAccessLevel, v))
}

// AccessLevelContains applies the Contains predicate on the "access_level" field.
func AccessLevelContains(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldContains(FieldAccessLevel, v))
}

// AccessLevelHasPrefix applies the HasPrefix predicate on the "access_level" field.
func AccessLevelHasPrefix(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldHasPrefix(FieldAccessLevel, v))
}

// AccessLevelHasSuffix applies the HasSuffix predicate on the "access_level" field.
func AccessLevelHasSuffix(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldHasSuffix(FieldAccessLevel, v))
}

// AccessLevelEqualFold applies the EqualFold predicate on the "access_level" field.
func AccessLevelEqualFold(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEqualFold(FieldAccessLevel, v))
}

// AccessLevelContainsFold applies the ContainsFold predicate on the "access_level" field.
func AccessLevelContainsFold(v string) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldContainsFold(FieldAccessLevel, v))
}

// GrantedByUserIDEQ applies the EQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDNEQ applies the NEQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDNEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDIn applies the In predicate on the "granted_by_user_id" field.
func GrantedByUserIDIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDNotIn applies the NotIn predicate on the "granted_by_user_id" field.
func GrantedByUserIDNotIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDIsNil applies the IsNil predicate on the "granted_by_user_id" field.
func GrantedByUserIDIsNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIsNull(FieldGrantedByUserID))
}

// GrantedByUserIDNotNil applies the NotNil predicate on the "granted_by_user_id" field.
func GrantedByUserIDNotNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotNull(FieldGrantedByUserID))
}

// GrantedByServicePrincipalIDEQ applies the EQ predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldGrantedByServicePrincipalID, v))
}

// GrantedByServicePrincipalIDNEQ applies the NEQ predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNEQ(v int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldGrantedByServicePrincipalID, v))
}

// GrantedByServicePrincipalIDIn applies the In predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldGrantedByServicePrincipalID, vs...))
}

// GrantedByServicePrincipalIDNotIn applies the NotIn predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNotIn(vs ...int64) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldGrantedByServicePrincipalID, vs...))
}

// GrantedByServicePrincipalIDIsNil applies the IsNil predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDIsNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIsNull(FieldGrantedByServicePrincipalID))
}

// GrantedByServicePrincipalIDNotNil applies the NotNil predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNotNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotNull(FieldGrantedByServicePrincipalID))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.FieldNotNull(FieldExpiresAt))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGranteeUser applies the HasEdge predicate on the "grantee_user" edge.
func HasGranteeUser() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GranteeUserTable, GranteeUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGranteeUserWith applies the HasEdge predicate on the "grantee_user" edge with a given conditions (other predicates).
func HasGranteeUserWith(preds ...predicate.User) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := newGranteeUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGranteeRole applies the HasEdge predicate on the "grantee_role" edge.
func HasGranteeRole() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GranteeRoleTable, GranteeRoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGranteeRoleWith applies the HasEdge predicate on the "grantee_role" edge with a given conditions (other predicates).
func HasGranteeRoleWith(preds ...predicate.Role) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := newGranteeRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantedByUser applies the HasEdge predicate on the "granted_by_user" edge.
func HasGrantedByUser() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GrantedByUserTable, GrantedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedByUserWith applies the HasEdge predicate on the "granted_by_user" edge with a given conditions (other predicates).
func HasGrantedByUserWith(preds ...predicate.User) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := newGrantedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantedByServicePrincipal applies the HasEdge predicate on the "granted_by_service_principal" edge.
func HasGrantedByServicePrincipal() predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GrantedByServicePrincipalTable, GrantedByServicePrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedByServicePrincipalWith applies the HasEdge predicate on the "granted_by_service_principal" edge with a given conditions (other predicates).
func HasGrantedByServicePrincipalWith(preds ...predicate.ServicePrincipal) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(func(s *sql.Selector) {
		step := newGrantedByServicePrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupAccessGrant) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupAccessGrant) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupAccessGrant) predicate.GroupAccessGrant {
	return predicate.GroupAccessGrant(sql.NotPredicates(p))
}
