// Code generated by ent, DO NOT EDIT.

package serviceprincipalworkerpermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the serviceprincipalworkerpermission type in the database.
	Label = "service_principal_worker_permission"
	// FieldServicePrincipalID holds the string denoting the service_principal_id field in the database.
	FieldServicePrincipalID = "service_principal_id"
	// FieldPermissionID holds the string denoting the permission_id field in the database.
	FieldPermissionID = "permission_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeServicePrincipal holds the string denoting the service_principal edge name in mutations.
	EdgeServicePrincipal = "service_principal"
	// EdgePermission holds the string denoting the permission edge name in mutations.
	EdgePermission = "permission"
	// ServicePrincipalFieldID holds the string denoting the ID field of the ServicePrincipal.
	ServicePrincipalFieldID = "id"
	// PermissionFieldID holds the string denoting the ID field of the Permission.
	PermissionFieldID = "id"
	// Table holds the table name of the serviceprincipalworkerpermission in the database.
	Table = "service_principal_worker_permissions"
	// ServicePrincipalTable is the table that holds the service_principal relation/edge.
	ServicePrincipalTable = "service_principal_worker_permissions"
	// ServicePrincipalInverseTable is the table name for the ServicePrincipal entity.
	// It exists in this package in order to avoid circular dependency with the "serviceprincipal" package.
	ServicePrincipalInverseTable = "service_principals"
	// ServicePrincipalColumn is the table column denoting the service_principal relation/edge.
	ServicePrincipalColumn = "service_principal_id"
	// PermissionTable is the table that holds the permission relation/edge.
	PermissionTable = "service_principal_worker_permissions"
	// PermissionInverseTable is the table name for the Permission entity.
	// It exists in this package in order to avoid circular dependency with the "permission" package.
	PermissionInverseTable = "permissions"
	// PermissionColumn is the table column denoting the permission relation/edge.
	PermissionColumn = "permission_id"
)

// Columns holds all SQL columns for serviceprincipalworkerpermission fields.
var Columns = []string{
	FieldServicePrincipalID,
	FieldPermissionID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ServicePrincipalWorkerPermission queries.
type OrderOption func(*sql.Selector)

// ByServicePrincipalID orders the results by the service_principal_id field.
func ByServicePrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServicePrincipalID, opts...).ToFunc()
}

// ByPermissionID orders the results by the permission_id field.
func ByPermissionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermissionID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByServicePrincipalField orders the results by service_principal field.
func ByServicePrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServicePrincipalStep(), sql.OrderByField(field, opts...))
	}
}

// ByPermissionField orders the results by permission field.
func ByPermissionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPermissionStep(), sql.OrderByField(field, opts...))
	}
}
func newServicePrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, ServicePrincipalColumn),
		sqlgraph.To(ServicePrincipalInverseTable, ServicePrincipalFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ServicePrincipalTable, ServicePrincipalColumn),
	)
}
func newPermissionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, PermissionColumn),
		sqlgraph.To(PermissionInverseTable, PermissionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PermissionTable, PermissionColumn),
	)
}
