package migrations

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestOpenAIQuotaAutoResetActorMigrationContract(t *testing.T) {
	content, err := FS.ReadFile("243_openai_quota_auto_reset_actor.sql")
	require.NoError(t, err)

	compact := strings.Join(strings.Fields(string(content)), " ")
	require.Contains(t, compact, "CREATE TABLE IF NOT EXISTS service_principal_worker_permissions")
	require.Contains(t, compact, "COUNT(*) = 3")
	require.Contains(t, compact, "PRIMARY KEY (service_principal_id, permission_id)")
	require.Contains(t, compact, "REFERENCES service_principals(id) ON DELETE CASCADE")
	require.Contains(t, compact, "REFERENCES permissions(id) ON DELETE CASCADE")
	require.Contains(t, compact, "unsafe existing service_principal_worker_permissions table shape")
	require.Contains(t, compact, "CREATE UNIQUE INDEX IF NOT EXISTS idx_audit_logs_openai_auto_reset_request_id")
	require.Contains(t, compact, "WHERE action = 'system.openai.reset_credit.auto' AND request_id <> ''")
	require.Contains(t, compact, "unsafe existing idx_audit_logs_openai_auto_reset_request_id index shape")

	require.Contains(t, compact, "CREATE OR REPLACE FUNCTION bump_worker_permission_principal_authz_version()")
	require.Contains(t, compact, "AFTER INSERT OR DELETE OR UPDATE OF service_principal_id, permission_id")
	require.Contains(t, compact, "SET authz_version = authz_version + 1")
	require.Contains(t, compact, "permission_exists IS DISTINCT FROM principal_exists")
	require.Contains(t, compact, "reserved_principal_status IS DISTINCT FROM 'active'")
	require.Contains(t, compact, "role_count <> 0")
	require.Contains(t, compact, "direct_permission_count <> 1")
	require.Contains(t, compact, "expected_direct_permission_count <> 1")
	require.NotContains(t, compact, "DELETE FROM service_principal_roles")

	require.Contains(t, compact, "CREATE TABLE IF NOT EXISTS openai_quota_auto_reset_protected_attempts")
	require.Contains(t, compact, "idempotency_record_id BIGINT NOT NULL")
	require.Contains(t, compact, "account_id BIGINT NOT NULL")
	require.Contains(t, compact, "protected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
	require.Contains(t, compact, "reconciled_at TIMESTAMPTZ")
	require.Contains(t, compact, "reconciliation_audit_request_id VARCHAR(64)")
	require.Contains(t, compact, "PRIMARY KEY (idempotency_record_id)")
	require.Contains(t, compact, "REFERENCES idempotency_records(id) ON DELETE RESTRICT")
	require.Contains(t, compact, "CHECK (account_id > 0)")
	require.Contains(t, compact, "(reconciled_at IS NULL) = (reconciliation_audit_request_id IS NULL)")
	require.Contains(t, compact, "unsafe existing openai_quota_auto_reset_protected_attempts table shape")
	require.Contains(t, compact, "CREATE TABLE IF NOT EXISTS openai_quota_auto_reset_protection_backfill")
	require.Contains(t, compact, "CHECK (completed)")
	require.Contains(t, compact, "unsafe existing openai_quota_auto_reset_protection_backfill table shape")

	identitySeed := strings.Index(compact, "INSERT INTO service_principals (code, name, status)")
	scopeTableLock := strings.Index(compact, "LOCK TABLE idempotency_records IN SHARE ROW EXCLUSIVE MODE")
	guardDrop := strings.Index(compact, "DROP TRIGGER IF EXISTS idempotency_records_openai_auto_reset_protected_attempt_guard")
	snapshotGate := strings.Index(compact, "IF snapshot_started THEN")
	markerValidation := strings.Index(compact, "OpenAI quota auto-reset protected marker identity is malformed")
	retryableFreeze := strings.Index(compact, "UPDATE idempotency_records AS record SET status = 'processing'")
	scopeMigration := strings.Index(compact, "UPDATE idempotency_records AS record SET scope =")
	require.Positive(t, identitySeed)
	require.Greater(t, scopeTableLock, identitySeed)
	require.Greater(t, guardDrop, scopeTableLock)
	require.Greater(t, snapshotGate, guardDrop)
	require.Greater(t, markerValidation, snapshotGate,
		"existing marker validation must remain outside one-time candidate discovery")
	require.Greater(t, retryableFreeze, markerValidation)
	require.Greater(t, scopeMigration, retryableFreeze)

	require.Contains(t, compact, "INSERT INTO openai_quota_auto_reset_protection_backfill (completed) VALUES (TRUE) ON CONFLICT (completed) DO NOTHING RETURNING completed INTO snapshot_started")
	require.Contains(t, compact, "snapshot_started := FOUND")
	require.Contains(t, compact, "record.idempotency_key_hash !~ '^[0-9a-f]{64}$'")
	require.Contains(t, compact, "record.request_fingerprint !~ '^[0-9a-f]{64}$'")
	require.Contains(t, compact, "LENGTH('openai_auto_reset_credit|account:')")
	require.Contains(t, compact, "LENGTH('openai_auto_reset_credit|service_principal:')")
	require.Contains(t, compact, "::NUMERIC > 9223372036854775807")
	require.Contains(t, compact, "OpenAI quota auto-reset protected attempt identity is malformed")
	require.Contains(t, compact, "'{\"account_id\":' || candidate.id::TEXT")
	require.Contains(t, compact, "'/system/openai/reset-credit/auto' || CHR(10)")
	require.Contains(t, compact, "'account:' || candidate.id::TEXT || CHR(10)")
	require.Contains(t, compact, "'service_principal:' || worker_principal_id::TEXT || CHR(10)")
	require.Contains(t, compact, "SELECT record.id, MIN(candidate.id)")
	require.Contains(t, compact, "GROUP BY record.id HAVING COUNT(*) = 1")
	require.Contains(t, compact, "OpenAI quota auto-reset protected attempt account provenance is not unique")
	require.Contains(t, compact, "OpenAI quota auto-reset protection snapshot is incomplete")
	require.Contains(t, compact, "INSERT INTO openai_quota_auto_reset_protected_attempts ( idempotency_record_id, account_id )")
	require.NotContains(t, compact, "SET request_fingerprint")

	require.Contains(t, compact, "record.scope = 'openai_auto_reset_credit'")
	require.Contains(t, compact, "record.scope = 'openai_auto_reset_credit|account:' || protected.account_id::TEXT")
	require.Contains(t, compact, "OpenAI quota auto-reset unresolved protected parent shape mismatch")
	require.Contains(t, compact, "record.status = 'processing' AND record.response_status IS NULL AND record.response_body IS NULL AND record.error_reason IS NULL")
	require.Contains(t, compact, "record.status = 'failed_retryable' AND record.response_status IS NULL AND record.response_body IS NULL")
	require.Contains(t, compact, "OpenAI quota auto-reset protected marker fingerprint mismatch")

	require.Contains(t, compact, "WHERE protected.reconciled_at IS NOT NULL")
	require.Contains(t, compact, "'reconcile-success:' || outcome.id::TEXT")
	require.Contains(t, compact, "OpenAI quota auto-reset reconciled outcome audit contract mismatch")
	require.Contains(t, compact, "OpenAI quota auto-reset reconciled parent outcome mismatch")
	require.Contains(t, compact, "outcome.expires_at IS DISTINCT FROM outcome.reconciled_at + INTERVAL '8 days'")
	require.Contains(t, compact, "LEFT(audit.request_id, LENGTH('reconcile-no-effect:')) = 'reconcile-no-effect:'")
	require.Contains(t, compact, "audit.extra ->> 'result_code' = 'reconciled_no_effect'")
	require.Contains(t, compact, "OpenAI quota auto-reset no-effect audit contract mismatch")
	require.Contains(t, compact, "OpenAI quota auto-reset no-effect audit cleanup mismatch")
	require.Contains(t, compact, "OpenAI quota auto-reset no-effect audit retained pending account state")

	guardFunction := strings.Index(compact, "CREATE OR REPLACE FUNCTION guard_openai_quota_auto_reset_protected_attempt()")
	guardTrigger := strings.Index(compact, "CREATE TRIGGER idempotency_records_openai_auto_reset_protected_attempt_guard")
	require.Greater(t, guardFunction, scopeMigration)
	require.Greater(t, guardTrigger, guardFunction)
	require.Contains(t, compact, "NEW.expires_at = protected_reconciled_at + INTERVAL '8 days'")
	require.Contains(t, compact, "protected OpenAI quota auto-reset attempt requires explicit reconciliation")
	require.Contains(t, compact, "BEFORE UPDATE OR DELETE ON idempotency_records")

	reconcileFunction := strings.Index(compact, "CREATE OR REPLACE FUNCTION reconcile_openai_quota_auto_reset_protected_attempt(")
	require.Greater(t, reconcileFunction, guardTrigger)
	require.Contains(t, compact, "p_idempotency_record_id IS NULL OR p_idempotency_record_id <= 0")
	require.Contains(t, compact, "p_actor_qualified_scope IS NULL")
	require.Contains(t, compact, "p_request_fingerprint IS NULL")
	require.Contains(t, compact, "p_account_id IS NULL OR p_account_id <= 0")
	require.Contains(t, compact, "p_audit_status_code IS NULL")
	require.Contains(t, compact, "'reconcile-success:' || p_idempotency_record_id::TEXT")
	require.Contains(t, compact, "JSONB_TYPEOF(p_audit_extra -> 'result_code') IS DISTINCT FROM 'string'")
	require.Contains(t, compact, "(p_audit_extra ->> 'windows_reset')::NUMERIC > 2147483647")
	require.Contains(t, compact, "canonical_response_body := CASE result_code")
	require.Contains(t, compact, "'result_code', 'no_credit', 'windows_reset', 0")
	require.Contains(t, compact, "'result_code', 'success', 'windows_reset', windows_reset")
	require.NotContains(t, compact, "'code', 'no_credit'")
	require.NotContains(t, compact, "'code', 'reconciled_success'")
	require.GreaterOrEqual(t, strings.Count(compact, "LOCK TABLE idempotency_records IN ROW EXCLUSIVE MODE"), 2)
	require.Contains(t, compact, "SET status = 'succeeded', response_status = 200, response_body = canonical_response_body")
	require.Contains(t, compact, "expires_at = statement_timestamp() + INTERVAL '8 days'")
	require.Contains(t, compact, "SECURITY INVOKER")

	discardFunction := strings.Index(compact, "CREATE OR REPLACE FUNCTION discard_openai_quota_auto_reset_protected_attempt_no_effect(")
	require.Greater(t, discardFunction, reconcileFunction)
	require.Contains(t, compact, "p_old_fleet_drained IS DISTINCT FROM TRUE")
	require.Contains(t, compact, "'reconcile-no-effect:' || p_idempotency_record_id::TEXT")
	require.Contains(t, compact, "p_audit_extra ->> 'result_code' IS DISTINCT FROM 'reconciled_no_effect'")
	require.Contains(t, compact, "p_audit_extra -> 'windows_reset' IS DISTINCT FROM TO_JSONB(0)")
	require.Contains(t, compact, "SET extra = account.extra - 'codex_auto_reset_credit_state'")
	require.Contains(t, compact, "OpenAI quota auto-reset discard record is missing and exact audit was not found")
	discardTail := compact[discardFunction:]
	markerDelete := strings.Index(discardTail, "DELETE FROM openai_quota_auto_reset_protected_attempts")
	parentExpire := strings.Index(discardTail, "SET status = 'failed_retryable'")
	parentDelete := strings.Index(discardTail, "DELETE FROM idempotency_records")
	require.Positive(t, markerDelete)
	require.Greater(t, parentExpire, markerDelete)
	require.Greater(t, parentDelete, parentExpire)

	require.GreaterOrEqual(t, strings.Count(compact, "DROP FUNCTION IF EXISTS reconcile_openai_quota_auto_reset_protected_attempt("), 2)
	require.Contains(t, compact, "reconcile_openai_quota_auto_reset_protected_attempt(bigint,text,text,bigint,timestamptz,text,integer,jsonb)")
	require.Contains(t, compact, "discard_openai_quota_auto_reset_protected_attempt_no_effect(bigint,text,text,bigint,timestamptz,text,jsonb,boolean)")
	require.Contains(t, compact, "procedure.prokind = 'f'")
	require.Contains(t, compact, "procedure.prorettype = 'void'::REGTYPE")
	require.Contains(t, compact, "REVOKE ALL ON FUNCTION %s FROM %I")
	require.Contains(t, compact, "privilege.grantee <> procedure.proowner")
	require.Contains(t, compact, "procedure.prosecdef")
	require.Contains(t, compact, "OpenAI quota auto-reset reconciliation function is not owner-only")

	require.Contains(t, compact, "CREATE OR REPLACE FUNCTION reject_legacy_openai_auto_reset_account_scope()")
	require.Contains(t, compact, "legacy OpenAI quota auto-reset account scope is fenced")
	require.Contains(t, compact, "BEFORE INSERT OR UPDATE OF scope ON idempotency_records")
	require.Contains(t, compact, "CREATE OR REPLACE FUNCTION guard_idempotency_record_expiry_delete()")
	require.Contains(t, compact, "IF OLD.expires_at > CURRENT_TIMESTAMP THEN RETURN NULL")
	require.Contains(t, compact, "IF OLD.status = 'succeeded' AND EXISTS")
	require.Contains(t, compact, "principal.code = 'openai_quota_auto_reset_worker'")
	require.Contains(t, compact, "account.extra -> 'codex_auto_reset_credit_state' ->> 'status' IN ('resetting', 'failed')")
	require.Contains(t, compact, "'oarc:' || account.id::TEXT || ':'")
	require.Contains(t, compact, "DROP TRIGGER IF EXISTS idempotency_records_expiry_delete_guard ON idempotency_records")
	require.Contains(t, compact, "CREATE TRIGGER idempotency_records_expiry_delete_guard BEFORE DELETE ON idempotency_records")
}
