// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountAccessGrant is the model entity for the AccountAccessGrant schema.
type AccountAccessGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GranteeUserID holds the value of the "grantee_user_id" field.
	GranteeUserID *int64 `json:"grantee_user_id,omitempty"`
	// GranteeRoleID holds the value of the "grantee_role_id" field.
	GranteeRoleID *int64 `json:"grantee_role_id,omitempty"`
	// AccessLevel holds the value of the "access_level" field.
	AccessLevel string `json:"access_level,omitempty"`
	// GrantedByUserID holds the value of the "granted_by_user_id" field.
	GrantedByUserID *int64 `json:"granted_by_user_id,omitempty"`
	// GrantedByServicePrincipalID holds the value of the "granted_by_service_principal_id" field.
	GrantedByServicePrincipalID *int64 `json:"granted_by_service_principal_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountAccessGrantQuery when eager-loading is set.
	Edges        AccountAccessGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountAccessGrantEdges holds the relations/edges for other nodes in the graph.
type AccountAccessGrantEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// GranteeUser holds the value of the grantee_user edge.
	GranteeUser *User `json:"grantee_user,omitempty"`
	// GranteeRole holds the value of the grantee_role edge.
	GranteeRole *Role `json:"grantee_role,omitempty"`
	// GrantedByUser holds the value of the granted_by_user edge.
	GrantedByUser *User `json:"granted_by_user,omitempty"`
	// GrantedByServicePrincipal holds the value of the granted_by_service_principal edge.
	GrantedByServicePrincipal *ServicePrincipal `json:"granted_by_service_principal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAccessGrantEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GranteeUserOrErr returns the GranteeUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAccessGrantEdges) GranteeUserOrErr() (*User, error) {
	if e.GranteeUser != nil {
		return e.GranteeUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "grantee_user"}
}

// GranteeRoleOrErr returns the GranteeRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAccessGrantEdges) GranteeRoleOrErr() (*Role, error) {
	if e.GranteeRole != nil {
		return e.GranteeRole, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "grantee_role"}
}

// GrantedByUserOrErr returns the GrantedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAccessGrantEdges) GrantedByUserOrErr() (*User, error) {
	if e.GrantedByUser != nil {
		return e.GrantedByUser, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "granted_by_user"}
}

// GrantedByServicePrincipalOrErr returns the GrantedByServicePrincipal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountAccessGrantEdges) GrantedByServicePrincipalOrErr() (*ServicePrincipal, error) {
	if e.GrantedByServicePrincipal != nil {
		return e.GrantedByServicePrincipal, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: serviceprincipal.Label}
	}
	return nil, &NotLoadedError{edge: "granted_by_service_principal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountAccessGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountaccessgrant.FieldID, accountaccessgrant.FieldAccountID, accountaccessgrant.FieldGranteeUserID, accountaccessgrant.FieldGranteeRoleID, accountaccessgrant.FieldGrantedByUserID, accountaccessgrant.FieldGrantedByServicePrincipalID:
			values[i] = new(sql.NullInt64)
		case accountaccessgrant.FieldAccessLevel:
			values[i] = new(sql.NullString)
		case accountaccessgrant.FieldCreatedAt, accountaccessgrant.FieldUpdatedAt, accountaccessgrant.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountAccessGrant fields.
func (_m *AccountAccessGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountaccessgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountaccessgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountaccessgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountaccessgrant.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountaccessgrant.FieldGranteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grantee_user_id", values[i])
			} else if value.Valid {
				_m.GranteeUserID = new(int64)
				*_m.GranteeUserID = value.Int64
			}
		case accountaccessgrant.FieldGranteeRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grantee_role_id", values[i])
			} else if value.Valid {
				_m.GranteeRoleID = new(int64)
				*_m.GranteeRoleID = value.Int64
			}
		case accountaccessgrant.FieldAccessLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_level", values[i])
			} else if value.Valid {
				_m.AccessLevel = value.String
			}
		case accountaccessgrant.FieldGrantedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_user_id", values[i])
			} else if value.Valid {
				_m.GrantedByUserID = new(int64)
				*_m.GrantedByUserID = value.Int64
			}
		case accountaccessgrant.FieldGrantedByServicePrincipalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_service_principal_id", values[i])
			} else if value.Valid {
				_m.GrantedByServicePrincipalID = new(int64)
				*_m.GrantedByServicePrincipalID = value.Int64
			}
		case accountaccessgrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountAccessGrant.
// This includes values selected through modifiers, order, etc.
func (_m *AccountAccessGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountAccessGrant entity.
func (_m *AccountAccessGrant) QueryAccount() *AccountQuery {
	return NewAccountAccessGrantClient(_m.config).QueryAccount(_m)
}

// QueryGranteeUser queries the "grantee_user" edge of the AccountAccessGrant entity.
func (_m *AccountAccessGrant) QueryGranteeUser() *UserQuery {
	return NewAccountAccessGrantClient(_m.config).QueryGranteeUser(_m)
}

// QueryGranteeRole queries the "grantee_role" edge of the AccountAccessGrant entity.
func (_m *AccountAccessGrant) QueryGranteeRole() *RoleQuery {
	return NewAccountAccessGrantClient(_m.config).QueryGranteeRole(_m)
}

// QueryGrantedByUser queries the "granted_by_user" edge of the AccountAccessGrant entity.
func (_m *AccountAccessGrant) QueryGrantedByUser() *UserQuery {
	return NewAccountAccessGrantClient(_m.config).QueryGrantedByUser(_m)
}

// QueryGrantedByServicePrincipal queries the "granted_by_service_principal" edge of the AccountAccessGrant entity.
func (_m *AccountAccessGrant) QueryGrantedByServicePrincipal() *ServicePrincipalQuery {
	return NewAccountAccessGrantClient(_m.config).QueryGrantedByServicePrincipal(_m)
}

// Update returns a builder for updating this AccountAccessGrant.
// Note that you need to call AccountAccessGrant.Unwrap() before calling this method if this AccountAccessGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountAccessGrant) Update() *AccountAccessGrantUpdateOne {
	return NewAccountAccessGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountAccessGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountAccessGrant) Unwrap() *AccountAccessGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountAccessGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountAccessGrant) String() string {
	var builder strings.Builder
	builder.WriteString("AccountAccessGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.GranteeUserID; v != nil {
		builder.WriteString("grantee_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GranteeRoleID; v != nil {
		builder.WriteString("grantee_role_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("access_level=")
	builder.WriteString(_m.AccessLevel)
	builder.WriteString(", ")
	if v := _m.GrantedByUserID; v != nil {
		builder.WriteString("granted_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GrantedByServicePrincipalID; v != nil {
		builder.WriteString("granted_by_service_principal_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccountAccessGrants is a parsable slice of AccountAccessGrant.
type AccountAccessGrants []*AccountAccessGrant
