// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountAccessGrantCreate is the builder for creating a AccountAccessGrant entity.
type AccountAccessGrantCreate struct {
	config
	mutation *AccountAccessGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountAccessGrantCreate) SetCreatedAt(v time.Time) *AccountAccessGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableCreatedAt(v *time.Time) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountAccessGrantCreate) SetUpdatedAt(v time.Time) *AccountAccessGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableUpdatedAt(v *time.Time) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountAccessGrantCreate) SetAccountID(v int64) *AccountAccessGrantCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGranteeUserID sets the "grantee_user_id" field.
func (_c *AccountAccessGrantCreate) SetGranteeUserID(v int64) *AccountAccessGrantCreate {
	_c.mutation.SetGranteeUserID(v)
	return _c
}

// SetNillableGranteeUserID sets the "grantee_user_id" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableGranteeUserID(v *int64) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetGranteeUserID(*v)
	}
	return _c
}

// SetGranteeRoleID sets the "grantee_role_id" field.
func (_c *AccountAccessGrantCreate) SetGranteeRoleID(v int64) *AccountAccessGrantCreate {
	_c.mutation.SetGranteeRoleID(v)
	return _c
}

// SetNillableGranteeRoleID sets the "grantee_role_id" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableGranteeRoleID(v *int64) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetGranteeRoleID(*v)
	}
	return _c
}

// SetAccessLevel sets the "access_level" field.
func (_c *AccountAccessGrantCreate) SetAccessLevel(v string) *AccountAccessGrantCreate {
	_c.mutation.SetAccessLevel(v)
	return _c
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_c *AccountAccessGrantCreate) SetGrantedByUserID(v int64) *AccountAccessGrantCreate {
	_c.mutation.SetGrantedByUserID(v)
	return _c
}

// SetNillableGrantedByUserID sets the "granted_by_user_id" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableGrantedByUserID(v *int64) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetGrantedByUserID(*v)
	}
	return _c
}

// SetGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field.
func (_c *AccountAccessGrantCreate) SetGrantedByServicePrincipalID(v int64) *AccountAccessGrantCreate {
	_c.mutation.SetGrantedByServicePrincipalID(v)
	return _c
}

// SetNillableGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableGrantedByServicePrincipalID(v *int64) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetGrantedByServicePrincipalID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AccountAccessGrantCreate) SetExpiresAt(v time.Time) *AccountAccessGrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *AccountAccessGrantCreate) SetNillableExpiresAt(v *time.Time) *AccountAccessGrantCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountAccessGrantCreate) SetAccount(v *Account) *AccountAccessGrantCreate {
	return _c.SetAccountID(v.ID)
}

// SetGranteeUser sets the "grantee_user" edge to the User entity.
func (_c *AccountAccessGrantCreate) SetGranteeUser(v *User) *AccountAccessGrantCreate {
	return _c.SetGranteeUserID(v.ID)
}

// SetGranteeRole sets the "grantee_role" edge to the Role entity.
func (_c *AccountAccessGrantCreate) SetGranteeRole(v *Role) *AccountAccessGrantCreate {
	return _c.SetGranteeRoleID(v.ID)
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_c *AccountAccessGrantCreate) SetGrantedByUser(v *User) *AccountAccessGrantCreate {
	return _c.SetGrantedByUserID(v.ID)
}

// SetGrantedByServicePrincipal sets the "granted_by_service_principal" edge to the ServicePrincipal entity.
func (_c *AccountAccessGrantCreate) SetGrantedByServicePrincipal(v *ServicePrincipal) *AccountAccessGrantCreate {
	return _c.SetGrantedByServicePrincipalID(v.ID)
}

// Mutation returns the AccountAccessGrantMutation object of the builder.
func (_c *AccountAccessGrantCreate) Mutation() *AccountAccessGrantMutation {
	return _c.mutation
}

// Save creates the AccountAccessGrant in the database.
func (_c *AccountAccessGrantCreate) Save(ctx context.Context) (*AccountAccessGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountAccessGrantCreate) SaveX(ctx context.Context) *AccountAccessGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAccessGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAccessGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountAccessGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountaccessgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountaccessgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountAccessGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountAccessGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountAccessGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountAccessGrant.account_id"`)}
	}
	if _, ok := _c.mutation.AccessLevel(); !ok {
		return &ValidationError{Name: "access_level", err: errors.New(`ent: missing required field "AccountAccessGrant.access_level"`)}
	}
	if v, ok := _c.mutation.AccessLevel(); ok {
		if err := accountaccessgrant.AccessLevelValidator(v); err != nil {
			return &ValidationError{Name: "access_level", err: fmt.Errorf(`ent: validator failed for field "AccountAccessGrant.access_level": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountAccessGrant.account"`)}
	}
	return nil
}

func (_c *AccountAccessGrantCreate) sqlSave(ctx context.Context) (*AccountAccessGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountAccessGrantCreate) createSpec() (*AccountAccessGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountAccessGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountaccessgrant.Table, sqlgraph.NewFieldSpec(accountaccessgrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountaccessgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountaccessgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccessLevel(); ok {
		_spec.SetField(accountaccessgrant.FieldAccessLevel, field.TypeString, value)
		_node.AccessLevel = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(accountaccessgrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountaccessgrant.AccountTable,
			Columns: []string{accountaccessgrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GranteeUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountaccessgrant.GranteeUserTable,
			Columns: []string{accountaccessgrant.GranteeUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GranteeUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GranteeRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountaccessgrant.GranteeRoleTable,
			Columns: []string{accountaccessgrant.GranteeRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GranteeRoleID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountaccessgrant.GrantedByUserTable,
			Columns: []string{accountaccessgrant.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantedByUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantedByServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountaccessgrant.GrantedByServicePrincipalTable,
			Columns: []string{accountaccessgrant.GrantedByServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantedByServicePrincipalID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountAccessGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountAccessGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountAccessGrantCreate) OnConflict(opts ...sql.ConflictOption) *AccountAccessGrantUpsertOne {
	_c.conflict = opts
	return &AccountAccessGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountAccessGrantCreate) OnConflictColumns(columns ...string) *AccountAccessGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountAccessGrantUpsertOne{
		create: _c,
	}
}

type (
	// AccountAccessGrantUpsertOne is the builder for "upsert"-ing
	//  one AccountAccessGrant node.
	AccountAccessGrantUpsertOne struct {
		create *AccountAccessGrantCreate
	}

	// AccountAccessGrantUpsert is the "OnConflict" setter.
	AccountAccessGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountAccessGrantUpsert) SetUpdatedAt(v time.Time) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateUpdatedAt() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountAccessGrantUpsert) SetAccountID(v int64) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateAccountID() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldAccountID)
	return u
}

// SetGranteeUserID sets the "grantee_user_id" field.
func (u *AccountAccessGrantUpsert) SetGranteeUserID(v int64) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldGranteeUserID, v)
	return u
}

// UpdateGranteeUserID sets the "grantee_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateGranteeUserID() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldGranteeUserID)
	return u
}

// ClearGranteeUserID clears the value of the "grantee_user_id" field.
func (u *AccountAccessGrantUpsert) ClearGranteeUserID() *AccountAccessGrantUpsert {
	u.SetNull(accountaccessgrant.FieldGranteeUserID)
	return u
}

// SetGranteeRoleID sets the "grantee_role_id" field.
func (u *AccountAccessGrantUpsert) SetGranteeRoleID(v int64) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldGranteeRoleID, v)
	return u
}

// UpdateGranteeRoleID sets the "grantee_role_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateGranteeRoleID() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldGranteeRoleID)
	return u
}

// ClearGranteeRoleID clears the value of the "grantee_role_id" field.
func (u *AccountAccessGrantUpsert) ClearGranteeRoleID() *AccountAccessGrantUpsert {
	u.SetNull(accountaccessgrant.FieldGranteeRoleID)
	return u
}

// SetAccessLevel sets the "access_level" field.
func (u *AccountAccessGrantUpsert) SetAccessLevel(v string) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldAccessLevel, v)
	return u
}

// UpdateAccessLevel sets the "access_level" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateAccessLevel() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldAccessLevel)
	return u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsert) SetGrantedByUserID(v int64) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldGrantedByUserID, v)
	return u
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateGrantedByUserID() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldGrantedByUserID)
	return u
}

// ClearGrantedByUserID clears the value of the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsert) ClearGrantedByUserID() *AccountAccessGrantUpsert {
	u.SetNull(accountaccessgrant.FieldGrantedByUserID)
	return u
}

// SetGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsert) SetGrantedByServicePrincipalID(v int64) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldGrantedByServicePrincipalID, v)
	return u
}

// UpdateGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateGrantedByServicePrincipalID() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldGrantedByServicePrincipalID)
	return u
}

// ClearGrantedByServicePrincipalID clears the value of the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsert) ClearGrantedByServicePrincipalID() *AccountAccessGrantUpsert {
	u.SetNull(accountaccessgrant.FieldGrantedByServicePrincipalID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountAccessGrantUpsert) SetExpiresAt(v time.Time) *AccountAccessGrantUpsert {
	u.Set(accountaccessgrant.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsert) UpdateExpiresAt() *AccountAccessGrantUpsert {
	u.SetExcluded(accountaccessgrant.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AccountAccessGrantUpsert) ClearExpiresAt() *AccountAccessGrantUpsert {
	u.SetNull(accountaccessgrant.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountAccessGrantUpsertOne) UpdateNewValues() *AccountAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountaccessgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountAccessGrantUpsertOne) Ignore() *AccountAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountAccessGrantUpsertOne) DoNothing() *AccountAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountAccessGrantCreate.OnConflict
// documentation for more info.
func (u *AccountAccessGrantUpsertOne) Update(set func(*AccountAccessGrantUpsert)) *AccountAccessGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountAccessGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountAccessGrantUpsertOne) SetUpdatedAt(v time.Time) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateUpdatedAt() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountAccessGrantUpsertOne) SetAccountID(v int64) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateAccountID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateAccountID()
	})
}

// SetGranteeUserID sets the "grantee_user_id" field.
func (u *AccountAccessGrantUpsertOne) SetGranteeUserID(v int64) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGranteeUserID(v)
	})
}

// UpdateGranteeUserID sets the "grantee_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateGranteeUserID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGranteeUserID()
	})
}

// ClearGranteeUserID clears the value of the "grantee_user_id" field.
func (u *AccountAccessGrantUpsertOne) ClearGranteeUserID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGranteeUserID()
	})
}

// SetGranteeRoleID sets the "grantee_role_id" field.
func (u *AccountAccessGrantUpsertOne) SetGranteeRoleID(v int64) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGranteeRoleID(v)
	})
}

// UpdateGranteeRoleID sets the "grantee_role_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateGranteeRoleID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGranteeRoleID()
	})
}

// ClearGranteeRoleID clears the value of the "grantee_role_id" field.
func (u *AccountAccessGrantUpsertOne) ClearGranteeRoleID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGranteeRoleID()
	})
}

// SetAccessLevel sets the "access_level" field.
func (u *AccountAccessGrantUpsertOne) SetAccessLevel(v string) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetAccessLevel(v)
	})
}

// UpdateAccessLevel sets the "access_level" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateAccessLevel() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateAccessLevel()
	})
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsertOne) SetGrantedByUserID(v int64) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGrantedByUserID(v)
	})
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateGrantedByUserID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGrantedByUserID()
	})
}

// ClearGrantedByUserID clears the value of the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsertOne) ClearGrantedByUserID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGrantedByUserID()
	})
}

// SetGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsertOne) SetGrantedByServicePrincipalID(v int64) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGrantedByServicePrincipalID(v)
	})
}

// UpdateGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateGrantedByServicePrincipalID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGrantedByServicePrincipalID()
	})
}

// ClearGrantedByServicePrincipalID clears the value of the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsertOne) ClearGrantedByServicePrincipalID() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGrantedByServicePrincipalID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountAccessGrantUpsertOne) SetExpiresAt(v time.Time) *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertOne) UpdateExpiresAt() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AccountAccessGrantUpsertOne) ClearExpiresAt() *AccountAccessGrantUpsertOne {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *AccountAccessGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountAccessGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountAccessGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountAccessGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountAccessGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountAccessGrantCreateBulk is the builder for creating many AccountAccessGrant entities in bulk.
type AccountAccessGrantCreateBulk struct {
	config
	err      error
	builders []*AccountAccessGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountAccessGrant entities in the database.
func (_c *AccountAccessGrantCreateBulk) Save(ctx context.Context) ([]*AccountAccessGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountAccessGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountAccessGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountAccessGrantCreateBulk) SaveX(ctx context.Context) []*AccountAccessGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAccessGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAccessGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountAccessGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountAccessGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountAccessGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountAccessGrantUpsertBulk {
	_c.conflict = opts
	return &AccountAccessGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountAccessGrantCreateBulk) OnConflictColumns(columns ...string) *AccountAccessGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountAccessGrantUpsertBulk{
		create: _c,
	}
}

// AccountAccessGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountAccessGrant nodes.
type AccountAccessGrantUpsertBulk struct {
	create *AccountAccessGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountAccessGrantUpsertBulk) UpdateNewValues() *AccountAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountaccessgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountAccessGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountAccessGrantUpsertBulk) Ignore() *AccountAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountAccessGrantUpsertBulk) DoNothing() *AccountAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountAccessGrantCreateBulk.OnConflict
// documentation for more info.
func (u *AccountAccessGrantUpsertBulk) Update(set func(*AccountAccessGrantUpsert)) *AccountAccessGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountAccessGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountAccessGrantUpsertBulk) SetUpdatedAt(v time.Time) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateUpdatedAt() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountAccessGrantUpsertBulk) SetAccountID(v int64) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateAccountID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateAccountID()
	})
}

// SetGranteeUserID sets the "grantee_user_id" field.
func (u *AccountAccessGrantUpsertBulk) SetGranteeUserID(v int64) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGranteeUserID(v)
	})
}

// UpdateGranteeUserID sets the "grantee_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateGranteeUserID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGranteeUserID()
	})
}

// ClearGranteeUserID clears the value of the "grantee_user_id" field.
func (u *AccountAccessGrantUpsertBulk) ClearGranteeUserID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGranteeUserID()
	})
}

// SetGranteeRoleID sets the "grantee_role_id" field.
func (u *AccountAccessGrantUpsertBulk) SetGranteeRoleID(v int64) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGranteeRoleID(v)
	})
}

// UpdateGranteeRoleID sets the "grantee_role_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateGranteeRoleID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGranteeRoleID()
	})
}

// ClearGranteeRoleID clears the value of the "grantee_role_id" field.
func (u *AccountAccessGrantUpsertBulk) ClearGranteeRoleID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGranteeRoleID()
	})
}

// SetAccessLevel sets the "access_level" field.
func (u *AccountAccessGrantUpsertBulk) SetAccessLevel(v string) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetAccessLevel(v)
	})
}

// UpdateAccessLevel sets the "access_level" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateAccessLevel() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateAccessLevel()
	})
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsertBulk) SetGrantedByUserID(v int64) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGrantedByUserID(v)
	})
}

// UpdateGrantedByUserID sets the "granted_by_user_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateGrantedByUserID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGrantedByUserID()
	})
}

// ClearGrantedByUserID clears the value of the "granted_by_user_id" field.
func (u *AccountAccessGrantUpsertBulk) ClearGrantedByUserID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGrantedByUserID()
	})
}

// SetGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsertBulk) SetGrantedByServicePrincipalID(v int64) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetGrantedByServicePrincipalID(v)
	})
}

// UpdateGrantedByServicePrincipalID sets the "granted_by_service_principal_id" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateGrantedByServicePrincipalID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateGrantedByServicePrincipalID()
	})
}

// ClearGrantedByServicePrincipalID clears the value of the "granted_by_service_principal_id" field.
func (u *AccountAccessGrantUpsertBulk) ClearGrantedByServicePrincipalID() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearGrantedByServicePrincipalID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountAccessGrantUpsertBulk) SetExpiresAt(v time.Time) *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountAccessGrantUpsertBulk) UpdateExpiresAt() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *AccountAccessGrantUpsertBulk) ClearExpiresAt() *AccountAccessGrantUpsertBulk {
	return u.Update(func(s *AccountAccessGrantUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *AccountAccessGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountAccessGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountAccessGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountAccessGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
