// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// GroupAccessGrant is the model entity for the GroupAccessGrant schema.
type GroupAccessGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// GranteeUserID holds the value of the "grantee_user_id" field.
	GranteeUserID *int64 `json:"grantee_user_id,omitempty"`
	// GranteeRoleID holds the value of the "grantee_role_id" field.
	GranteeRoleID *int64 `json:"grantee_role_id,omitempty"`
	// AccessLevel holds the value of the "access_level" field.
	AccessLevel string `json:"access_level,omitempty"`
	// GrantedByUserID holds the value of the "granted_by_user_id" field.
	GrantedByUserID *int64 `json:"granted_by_user_id,omitempty"`
	// GrantedByServicePrincipalID holds the value of the "granted_by_service_principal_id" field.
	GrantedByServicePrincipalID *int64 `json:"granted_by_service_principal_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupAccessGrantQuery when eager-loading is set.
	Edges        GroupAccessGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupAccessGrantEdges holds the relations/edges for other nodes in the graph.
type GroupAccessGrantEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// GranteeUser holds the value of the grantee_user edge.
	GranteeUser *User `json:"grantee_user,omitempty"`
	// GranteeRole holds the value of the grantee_role edge.
	GranteeRole *Role `json:"grantee_role,omitempty"`
	// GrantedByUser holds the value of the granted_by_user edge.
	GrantedByUser *User `json:"granted_by_user,omitempty"`
	// GrantedByServicePrincipal holds the value of the granted_by_service_principal edge.
	GrantedByServicePrincipal *ServicePrincipal `json:"granted_by_service_principal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupAccessGrantEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// GranteeUserOrErr returns the GranteeUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupAccessGrantEdges) GranteeUserOrErr() (*User, error) {
	if e.GranteeUser != nil {
		return e.GranteeUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "grantee_user"}
}

// GranteeRoleOrErr returns the GranteeRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupAccessGrantEdges) GranteeRoleOrErr() (*Role, error) {
	if e.GranteeRole != nil {
		return e.GranteeRole, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "grantee_role"}
}

// GrantedByUserOrErr returns the GrantedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupAccessGrantEdges) GrantedByUserOrErr() (*User, error) {
	if e.GrantedByUser != nil {
		return e.GrantedByUser, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "granted_by_user"}
}

// GrantedByServicePrincipalOrErr returns the GrantedByServicePrincipal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupAccessGrantEdges) GrantedByServicePrincipalOrErr() (*ServicePrincipal, error) {
	if e.GrantedByServicePrincipal != nil {
		return e.GrantedByServicePrincipal, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: serviceprincipal.Label}
	}
	return nil, &NotLoadedError{edge: "granted_by_service_principal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupAccessGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupaccessgrant.FieldID, groupaccessgrant.FieldGroupID, groupaccessgrant.FieldGranteeUserID, groupaccessgrant.FieldGranteeRoleID, groupaccessgrant.FieldGrantedByUserID, groupaccessgrant.FieldGrantedByServicePrincipalID:
			values[i] = new(sql.NullInt64)
		case groupaccessgrant.FieldAccessLevel:
			values[i] = new(sql.NullString)
		case groupaccessgrant.FieldCreatedAt, groupaccessgrant.FieldUpdatedAt, groupaccessgrant.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupAccessGrant fields.
func (_m *GroupAccessGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupaccessgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupaccessgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupaccessgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case groupaccessgrant.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupaccessgrant.FieldGranteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grantee_user_id", values[i])
			} else if value.Valid {
				_m.GranteeUserID = new(int64)
				*_m.GranteeUserID = value.Int64
			}
		case groupaccessgrant.FieldGranteeRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grantee_role_id", values[i])
			} else if value.Valid {
				_m.GranteeRoleID = new(int64)
				*_m.GranteeRoleID = value.Int64
			}
		case groupaccessgrant.FieldAccessLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_level", values[i])
			} else if value.Valid {
				_m.AccessLevel = value.String
			}
		case groupaccessgrant.FieldGrantedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_user_id", values[i])
			} else if value.Valid {
				_m.GrantedByUserID = new(int64)
				*_m.GrantedByUserID = value.Int64
			}
		case groupaccessgrant.FieldGrantedByServicePrincipalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_service_principal_id", values[i])
			} else if value.Valid {
				_m.GrantedByServicePrincipalID = new(int64)
				*_m.GrantedByServicePrincipalID = value.Int64
			}
		case groupaccessgrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupAccessGrant.
// This includes values selected through modifiers, order, etc.
func (_m *GroupAccessGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupAccessGrant entity.
func (_m *GroupAccessGrant) QueryGroup() *GroupQuery {
	return NewGroupAccessGrantClient(_m.config).QueryGroup(_m)
}

// QueryGranteeUser queries the "grantee_user" edge of the GroupAccessGrant entity.
func (_m *GroupAccessGrant) QueryGranteeUser() *UserQuery {
	return NewGroupAccessGrantClient(_m.config).QueryGranteeUser(_m)
}

// QueryGranteeRole queries the "grantee_role" edge of the GroupAccessGrant entity.
func (_m *GroupAccessGrant) QueryGranteeRole() *RoleQuery {
	return NewGroupAccessGrantClient(_m.config).QueryGranteeRole(_m)
}

// QueryGrantedByUser queries the "granted_by_user" edge of the GroupAccessGrant entity.
func (_m *GroupAccessGrant) QueryGrantedByUser() *UserQuery {
	return NewGroupAccessGrantClient(_m.config).QueryGrantedByUser(_m)
}

// QueryGrantedByServicePrincipal queries the "granted_by_service_principal" edge of the GroupAccessGrant entity.
func (_m *GroupAccessGrant) QueryGrantedByServicePrincipal() *ServicePrincipalQuery {
	return NewGroupAccessGrantClient(_m.config).QueryGrantedByServicePrincipal(_m)
}

// Update returns a builder for updating this GroupAccessGrant.
// Note that you need to call GroupAccessGrant.Unwrap() before calling this method if this GroupAccessGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupAccessGrant) Update() *GroupAccessGrantUpdateOne {
	return NewGroupAccessGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupAccessGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupAccessGrant) Unwrap() *GroupAccessGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupAccessGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupAccessGrant) String() string {
	var builder strings.Builder
	builder.WriteString("GroupAccessGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.GranteeUserID; v != nil {
		builder.WriteString("grantee_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GranteeRoleID; v != nil {
		builder.WriteString("grantee_role_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("access_level=")
	builder.WriteString(_m.AccessLevel)
	builder.WriteString(", ")
	if v := _m.GrantedByUserID; v != nil {
		builder.WriteString("granted_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GrantedByServicePrincipalID; v != nil {
		builder.WriteString("granted_by_service_principal_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupAccessGrants is a parsable slice of GroupAccessGrant.
type GroupAccessGrants []*GroupAccessGrant
