// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupaccessgrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// GroupAccessGrantQuery is the builder for querying GroupAccessGrant entities.
type GroupAccessGrantQuery struct {
	config
	ctx                           *QueryContext
	order                         []groupaccessgrant.OrderOption
	inters                        []Interceptor
	predicates                    []predicate.GroupAccessGrant
	withGroup                     *GroupQuery
	withGranteeUser               *UserQuery
	withGranteeRole               *RoleQuery
	withGrantedByUser             *UserQuery
	withGrantedByServicePrincipal *ServicePrincipalQuery
	modifiers                     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupAccessGrantQuery builder.
func (_q *GroupAccessGrantQuery) Where(ps ...predicate.GroupAccessGrant) *GroupAccessGrantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GroupAccessGrantQuery) Limit(limit int) *GroupAccessGrantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GroupAccessGrantQuery) Offset(offset int) *GroupAccessGrantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GroupAccessGrantQuery) Unique(unique bool) *GroupAccessGrantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GroupAccessGrantQuery) Order(o ...groupaccessgrant.OrderOption) *GroupAccessGrantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *GroupAccessGrantQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupaccessgrant.Table, groupaccessgrant.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupaccessgrant.GroupTable, groupaccessgrant.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGranteeUser chains the current query on the "grantee_user" edge.
func (_q *GroupAccessGrantQuery) QueryGranteeUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupaccessgrant.Table, groupaccessgrant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupaccessgrant.GranteeUserTable, groupaccessgrant.GranteeUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGranteeRole chains the current query on the "grantee_role" edge.
func (_q *GroupAccessGrantQuery) QueryGranteeRole() *RoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupaccessgrant.Table, groupaccessgrant.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupaccessgrant.GranteeRoleTable, groupaccessgrant.GranteeRoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrantedByUser chains the current query on the "granted_by_user" edge.
func (_q *GroupAccessGrantQuery) QueryGrantedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupaccessgrant.Table, groupaccessgrant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupaccessgrant.GrantedByUserTable, groupaccessgrant.GrantedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrantedByServicePrincipal chains the current query on the "granted_by_service_principal" edge.
func (_q *GroupAccessGrantQuery) QueryGrantedByServicePrincipal() *ServicePrincipalQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupaccessgrant.Table, groupaccessgrant.FieldID, selector),
			sqlgraph.To(serviceprincipal.Table, serviceprincipal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupaccessgrant.GrantedByServicePrincipalTable, groupaccessgrant.GrantedByServicePrincipalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupAccessGrant entity from the query.
// Returns a *NotFoundError when no GroupAccessGrant was found.
func (_q *GroupAccessGrantQuery) First(ctx context.Context) (*GroupAccessGrant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupaccessgrant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) FirstX(ctx context.Context) *GroupAccessGrant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupAccessGrant ID from the query.
// Returns a *NotFoundError when no GroupAccessGrant ID was found.
func (_q *GroupAccessGrantQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupaccessgrant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupAccessGrant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupAccessGrant entity is found.
// Returns a *NotFoundError when no GroupAccessGrant entities are found.
func (_q *GroupAccessGrantQuery) Only(ctx context.Context) (*GroupAccessGrant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupaccessgrant.Label}
	default:
		return nil, &NotSingularError{groupaccessgrant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) OnlyX(ctx context.Context) *GroupAccessGrant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupAccessGrant ID in the query.
// Returns a *NotSingularError when more than one GroupAccessGrant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GroupAccessGrantQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupaccessgrant.Label}
	default:
		err = &NotSingularError{groupaccessgrant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupAccessGrants.
func (_q *GroupAccessGrantQuery) All(ctx context.Context) ([]*GroupAccessGrant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupAccessGrant, *GroupAccessGrantQuery]()
	return withInterceptors[[]*GroupAccessGrant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) AllX(ctx context.Context) []*GroupAccessGrant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupAccessGrant IDs.
func (_q *GroupAccessGrantQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(groupaccessgrant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GroupAccessGrantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GroupAccessGrantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GroupAccessGrantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GroupAccessGrantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupAccessGrantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GroupAccessGrantQuery) Clone() *GroupAccessGrantQuery {
	if _q == nil {
		return nil
	}
	return &GroupAccessGrantQuery{
		config:                        _q.config,
		ctx:                           _q.ctx.Clone(),
		order:                         append([]groupaccessgrant.OrderOption{}, _q.order...),
		inters:                        append([]Interceptor{}, _q.inters...),
		predicates:                    append([]predicate.GroupAccessGrant{}, _q.predicates...),
		withGroup:                     _q.withGroup.Clone(),
		withGranteeUser:               _q.withGranteeUser.Clone(),
		withGranteeRole:               _q.withGranteeRole.Clone(),
		withGrantedByUser:             _q.withGrantedByUser.Clone(),
		withGrantedByServicePrincipal: _q.withGrantedByServicePrincipal.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupAccessGrantQuery) WithGroup(opts ...func(*GroupQuery)) *GroupAccessGrantQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithGranteeUser tells the query-builder to eager-load the nodes that are connected to
// the "grantee_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupAccessGrantQuery) WithGranteeUser(opts ...func(*UserQuery)) *GroupAccessGrantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGranteeUser = query
	return _q
}

// WithGranteeRole tells the query-builder to eager-load the nodes that are connected to
// the "grantee_role" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupAccessGrantQuery) WithGranteeRole(opts ...func(*RoleQuery)) *GroupAccessGrantQuery {
	query := (&RoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGranteeRole = query
	return _q
}

// WithGrantedByUser tells the query-builder to eager-load the nodes that are connected to
// the "granted_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupAccessGrantQuery) WithGrantedByUser(opts ...func(*UserQuery)) *GroupAccessGrantQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrantedByUser = query
	return _q
}

// WithGrantedByServicePrincipal tells the query-builder to eager-load the nodes that are connected to
// the "granted_by_service_principal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupAccessGrantQuery) WithGrantedByServicePrincipal(opts ...func(*ServicePrincipalQuery)) *GroupAccessGrantQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrantedByServicePrincipal = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupAccessGrant.Query().
//		GroupBy(groupaccessgrant.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GroupAccessGrantQuery) GroupBy(field string, fields ...string) *GroupAccessGrantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupAccessGrantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = groupaccessgrant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GroupAccessGrant.Query().
//		Select(groupaccessgrant.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *GroupAccessGrantQuery) Select(fields ...string) *GroupAccessGrantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GroupAccessGrantSelect{GroupAccessGrantQuery: _q}
	sbuild.label = groupaccessgrant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupAccessGrantSelect configured with the given aggregations.
func (_q *GroupAccessGrantQuery) Aggregate(fns ...AggregateFunc) *GroupAccessGrantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GroupAccessGrantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !groupaccessgrant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GroupAccessGrantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupAccessGrant, error) {
	var (
		nodes       = []*GroupAccessGrant{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withGroup != nil,
			_q.withGranteeUser != nil,
			_q.withGranteeRole != nil,
			_q.withGrantedByUser != nil,
			_q.withGrantedByServicePrincipal != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupAccessGrant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupAccessGrant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *GroupAccessGrant, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGranteeUser; query != nil {
		if err := _q.loadGranteeUser(ctx, query, nodes, nil,
			func(n *GroupAccessGrant, e *User) { n.Edges.GranteeUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGranteeRole; query != nil {
		if err := _q.loadGranteeRole(ctx, query, nodes, nil,
			func(n *GroupAccessGrant, e *Role) { n.Edges.GranteeRole = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrantedByUser; query != nil {
		if err := _q.loadGrantedByUser(ctx, query, nodes, nil,
			func(n *GroupAccessGrant, e *User) { n.Edges.GrantedByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrantedByServicePrincipal; query != nil {
		if err := _q.loadGrantedByServicePrincipal(ctx, query, nodes, nil,
			func(n *GroupAccessGrant, e *ServicePrincipal) { n.Edges.GrantedByServicePrincipal = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GroupAccessGrantQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*GroupAccessGrant, init func(*GroupAccessGrant), assign func(*GroupAccessGrant, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupAccessGrant)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupAccessGrantQuery) loadGranteeUser(ctx context.Context, query *UserQuery, nodes []*GroupAccessGrant, init func(*GroupAccessGrant), assign func(*GroupAccessGrant, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupAccessGrant)
	for i := range nodes {
		if nodes[i].GranteeUserID == nil {
			continue
		}
		fk := *nodes[i].GranteeUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "grantee_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupAccessGrantQuery) loadGranteeRole(ctx context.Context, query *RoleQuery, nodes []*GroupAccessGrant, init func(*GroupAccessGrant), assign func(*GroupAccessGrant, *Role)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupAccessGrant)
	for i := range nodes {
		if nodes[i].GranteeRoleID == nil {
			continue
		}
		fk := *nodes[i].GranteeRoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "grantee_role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupAccessGrantQuery) loadGrantedByUser(ctx context.Context, query *UserQuery, nodes []*GroupAccessGrant, init func(*GroupAccessGrant), assign func(*GroupAccessGrant, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupAccessGrant)
	for i := range nodes {
		if nodes[i].GrantedByUserID == nil {
			continue
		}
		fk := *nodes[i].GrantedByUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "granted_by_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupAccessGrantQuery) loadGrantedByServicePrincipal(ctx context.Context, query *ServicePrincipalQuery, nodes []*GroupAccessGrant, init func(*GroupAccessGrant), assign func(*GroupAccessGrant, *ServicePrincipal)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupAccessGrant)
	for i := range nodes {
		if nodes[i].GrantedByServicePrincipalID == nil {
			continue
		}
		fk := *nodes[i].GrantedByServicePrincipalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(serviceprincipal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "granted_by_service_principal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GroupAccessGrantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GroupAccessGrantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupaccessgrant.Table, groupaccessgrant.Columns, sqlgraph.NewFieldSpec(groupaccessgrant.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupaccessgrant.FieldID)
		for i := range fields {
			if fields[i] != groupaccessgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(groupaccessgrant.FieldGroupID)
		}
		if _q.withGranteeUser != nil {
			_spec.Node.AddColumnOnce(groupaccessgrant.FieldGranteeUserID)
		}
		if _q.withGranteeRole != nil {
			_spec.Node.AddColumnOnce(groupaccessgrant.FieldGranteeRoleID)
		}
		if _q.withGrantedByUser != nil {
			_spec.Node.AddColumnOnce(groupaccessgrant.FieldGrantedByUserID)
		}
		if _q.withGrantedByServicePrincipal != nil {
			_spec.Node.AddColumnOnce(groupaccessgrant.FieldGrantedByServicePrincipalID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GroupAccessGrantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(groupaccessgrant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = groupaccessgrant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *GroupAccessGrantQuery) ForUpdate(opts ...sql.LockOption) *GroupAccessGrantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *GroupAccessGrantQuery) ForShare(opts ...sql.LockOption) *GroupAccessGrantQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// GroupAccessGrantGroupBy is the group-by builder for GroupAccessGrant entities.
type GroupAccessGrantGroupBy struct {
	selector
	build *GroupAccessGrantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GroupAccessGrantGroupBy) Aggregate(fns ...AggregateFunc) *GroupAccessGrantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GroupAccessGrantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupAccessGrantQuery, *GroupAccessGrantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GroupAccessGrantGroupBy) sqlScan(ctx context.Context, root *GroupAccessGrantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupAccessGrantSelect is the builder for selecting fields of GroupAccessGrant entities.
type GroupAccessGrantSelect struct {
	*GroupAccessGrantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GroupAccessGrantSelect) Aggregate(fns ...AggregateFunc) *GroupAccessGrantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GroupAccessGrantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupAccessGrantQuery, *GroupAccessGrantSelect](ctx, _s.GroupAccessGrantQuery, _s, _s.inters, v)
}

func (_s *GroupAccessGrantSelect) sqlScan(ctx context.Context, root *GroupAccessGrantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
