// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourceauthorizationevent"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResourceAuthorizationEventQuery is the builder for querying ResourceAuthorizationEvent entities.
type ResourceAuthorizationEventQuery struct {
	config
	ctx                       *QueryContext
	order                     []resourceauthorizationevent.OrderOption
	inters                    []Interceptor
	predicates                []predicate.ResourceAuthorizationEvent
	withAccount               *AccountQuery
	withGroup                 *GroupQuery
	withActorUser             *UserQuery
	withActorServicePrincipal *ServicePrincipalQuery
	withResourceOwner         *UserQuery
	modifiers                 []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResourceAuthorizationEventQuery builder.
func (_q *ResourceAuthorizationEventQuery) Where(ps ...predicate.ResourceAuthorizationEvent) *ResourceAuthorizationEventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResourceAuthorizationEventQuery) Limit(limit int) *ResourceAuthorizationEventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResourceAuthorizationEventQuery) Offset(offset int) *ResourceAuthorizationEventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResourceAuthorizationEventQuery) Unique(unique bool) *ResourceAuthorizationEventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResourceAuthorizationEventQuery) Order(o ...resourceauthorizationevent.OrderOption) *ResourceAuthorizationEventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccount chains the current query on the "account" edge.
func (_q *ResourceAuthorizationEventQuery) QueryAccount() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceauthorizationevent.Table, resourceauthorizationevent.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, resourceauthorizationevent.AccountTable, resourceauthorizationevent.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *ResourceAuthorizationEventQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceauthorizationevent.Table, resourceauthorizationevent.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, resourceauthorizationevent.GroupTable, resourceauthorizationevent.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActorUser chains the current query on the "actor_user" edge.
func (_q *ResourceAuthorizationEventQuery) QueryActorUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceauthorizationevent.Table, resourceauthorizationevent.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, resourceauthorizationevent.ActorUserTable, resourceauthorizationevent.ActorUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActorServicePrincipal chains the current query on the "actor_service_principal" edge.
func (_q *ResourceAuthorizationEventQuery) QueryActorServicePrincipal() *ServicePrincipalQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceauthorizationevent.Table, resourceauthorizationevent.FieldID, selector),
			sqlgraph.To(serviceprincipal.Table, serviceprincipal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, resourceauthorizationevent.ActorServicePrincipalTable, resourceauthorizationevent.ActorServicePrincipalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResourceOwner chains the current query on the "resource_owner" edge.
func (_q *ResourceAuthorizationEventQuery) QueryResourceOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceauthorizationevent.Table, resourceauthorizationevent.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, resourceauthorizationevent.ResourceOwnerTable, resourceauthorizationevent.ResourceOwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResourceAuthorizationEvent entity from the query.
// Returns a *NotFoundError when no ResourceAuthorizationEvent was found.
func (_q *ResourceAuthorizationEventQuery) First(ctx context.Context) (*ResourceAuthorizationEvent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resourceauthorizationevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) FirstX(ctx context.Context) *ResourceAuthorizationEvent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResourceAuthorizationEvent ID from the query.
// Returns a *NotFoundError when no ResourceAuthorizationEvent ID was found.
func (_q *ResourceAuthorizationEventQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resourceauthorizationevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResourceAuthorizationEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResourceAuthorizationEvent entity is found.
// Returns a *NotFoundError when no ResourceAuthorizationEvent entities are found.
func (_q *ResourceAuthorizationEventQuery) Only(ctx context.Context) (*ResourceAuthorizationEvent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resourceauthorizationevent.Label}
	default:
		return nil, &NotSingularError{resourceauthorizationevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) OnlyX(ctx context.Context) *ResourceAuthorizationEvent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResourceAuthorizationEvent ID in the query.
// Returns a *NotSingularError when more than one ResourceAuthorizationEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResourceAuthorizationEventQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resourceauthorizationevent.Label}
	default:
		err = &NotSingularError{resourceauthorizationevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResourceAuthorizationEvents.
func (_q *ResourceAuthorizationEventQuery) All(ctx context.Context) ([]*ResourceAuthorizationEvent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ResourceAuthorizationEvent, *ResourceAuthorizationEventQuery]()
	return withInterceptors[[]*ResourceAuthorizationEvent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) AllX(ctx context.Context) []*ResourceAuthorizationEvent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResourceAuthorizationEvent IDs.
func (_q *ResourceAuthorizationEventQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(resourceauthorizationevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResourceAuthorizationEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResourceAuthorizationEventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResourceAuthorizationEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResourceAuthorizationEventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResourceAuthorizationEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResourceAuthorizationEventQuery) Clone() *ResourceAuthorizationEventQuery {
	if _q == nil {
		return nil
	}
	return &ResourceAuthorizationEventQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]resourceauthorizationevent.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.ResourceAuthorizationEvent{}, _q.predicates...),
		withAccount:               _q.withAccount.Clone(),
		withGroup:                 _q.withGroup.Clone(),
		withActorUser:             _q.withActorUser.Clone(),
		withActorServicePrincipal: _q.withActorServicePrincipal.Clone(),
		withResourceOwner:         _q.withResourceOwner.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceAuthorizationEventQuery) WithAccount(opts ...func(*AccountQuery)) *ResourceAuthorizationEventQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccount = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceAuthorizationEventQuery) WithGroup(opts ...func(*GroupQuery)) *ResourceAuthorizationEventQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithActorUser tells the query-builder to eager-load the nodes that are connected to
// the "actor_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceAuthorizationEventQuery) WithActorUser(opts ...func(*UserQuery)) *ResourceAuthorizationEventQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActorUser = query
	return _q
}

// WithActorServicePrincipal tells the query-builder to eager-load the nodes that are connected to
// the "actor_service_principal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceAuthorizationEventQuery) WithActorServicePrincipal(opts ...func(*ServicePrincipalQuery)) *ResourceAuthorizationEventQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActorServicePrincipal = query
	return _q
}

// WithResourceOwner tells the query-builder to eager-load the nodes that are connected to
// the "resource_owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceAuthorizationEventQuery) WithResourceOwner(opts ...func(*UserQuery)) *ResourceAuthorizationEventQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResourceOwner = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResourceAuthorizationEvent.Query().
//		GroupBy(resourceauthorizationevent.FieldAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResourceAuthorizationEventQuery) GroupBy(field string, fields ...string) *ResourceAuthorizationEventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResourceAuthorizationEventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = resourceauthorizationevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//	}
//
//	client.ResourceAuthorizationEvent.Query().
//		Select(resourceauthorizationevent.FieldAccountID).
//		Scan(ctx, &v)
func (_q *ResourceAuthorizationEventQuery) Select(fields ...string) *ResourceAuthorizationEventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResourceAuthorizationEventSelect{ResourceAuthorizationEventQuery: _q}
	sbuild.label = resourceauthorizationevent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResourceAuthorizationEventSelect configured with the given aggregations.
func (_q *ResourceAuthorizationEventQuery) Aggregate(fns ...AggregateFunc) *ResourceAuthorizationEventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResourceAuthorizationEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !resourceauthorizationevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResourceAuthorizationEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResourceAuthorizationEvent, error) {
	var (
		nodes       = []*ResourceAuthorizationEvent{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withAccount != nil,
			_q.withGroup != nil,
			_q.withActorUser != nil,
			_q.withActorServicePrincipal != nil,
			_q.withResourceOwner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResourceAuthorizationEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResourceAuthorizationEvent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccount; query != nil {
		if err := _q.loadAccount(ctx, query, nodes, nil,
			func(n *ResourceAuthorizationEvent, e *Account) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *ResourceAuthorizationEvent, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withActorUser; query != nil {
		if err := _q.loadActorUser(ctx, query, nodes, nil,
			func(n *ResourceAuthorizationEvent, e *User) { n.Edges.ActorUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withActorServicePrincipal; query != nil {
		if err := _q.loadActorServicePrincipal(ctx, query, nodes, nil,
			func(n *ResourceAuthorizationEvent, e *ServicePrincipal) { n.Edges.ActorServicePrincipal = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withResourceOwner; query != nil {
		if err := _q.loadResourceOwner(ctx, query, nodes, nil,
			func(n *ResourceAuthorizationEvent, e *User) { n.Edges.ResourceOwner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResourceAuthorizationEventQuery) loadAccount(ctx context.Context, query *AccountQuery, nodes []*ResourceAuthorizationEvent, init func(*ResourceAuthorizationEvent), assign func(*ResourceAuthorizationEvent, *Account)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResourceAuthorizationEvent)
	for i := range nodes {
		if nodes[i].AccountID == nil {
			continue
		}
		fk := *nodes[i].AccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResourceAuthorizationEventQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*ResourceAuthorizationEvent, init func(*ResourceAuthorizationEvent), assign func(*ResourceAuthorizationEvent, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResourceAuthorizationEvent)
	for i := range nodes {
		if nodes[i].GroupID == nil {
			continue
		}
		fk := *nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResourceAuthorizationEventQuery) loadActorUser(ctx context.Context, query *UserQuery, nodes []*ResourceAuthorizationEvent, init func(*ResourceAuthorizationEvent), assign func(*ResourceAuthorizationEvent, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResourceAuthorizationEvent)
	for i := range nodes {
		if nodes[i].ActorUserID == nil {
			continue
		}
		fk := *nodes[i].ActorUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "actor_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResourceAuthorizationEventQuery) loadActorServicePrincipal(ctx context.Context, query *ServicePrincipalQuery, nodes []*ResourceAuthorizationEvent, init func(*ResourceAuthorizationEvent), assign func(*ResourceAuthorizationEvent, *ServicePrincipal)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResourceAuthorizationEvent)
	for i := range nodes {
		if nodes[i].ActorServicePrincipalID == nil {
			continue
		}
		fk := *nodes[i].ActorServicePrincipalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(serviceprincipal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "actor_service_principal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResourceAuthorizationEventQuery) loadResourceOwner(ctx context.Context, query *UserQuery, nodes []*ResourceAuthorizationEvent, init func(*ResourceAuthorizationEvent), assign func(*ResourceAuthorizationEvent, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResourceAuthorizationEvent)
	for i := range nodes {
		if nodes[i].ResourceOwnerUserID == nil {
			continue
		}
		fk := *nodes[i].ResourceOwnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "resource_owner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ResourceAuthorizationEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResourceAuthorizationEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resourceauthorizationevent.Table, resourceauthorizationevent.Columns, sqlgraph.NewFieldSpec(resourceauthorizationevent.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceauthorizationevent.FieldID)
		for i := range fields {
			if fields[i] != resourceauthorizationevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAccount != nil {
			_spec.Node.AddColumnOnce(resourceauthorizationevent.FieldAccountID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(resourceauthorizationevent.FieldGroupID)
		}
		if _q.withActorUser != nil {
			_spec.Node.AddColumnOnce(resourceauthorizationevent.FieldActorUserID)
		}
		if _q.withActorServicePrincipal != nil {
			_spec.Node.AddColumnOnce(resourceauthorizationevent.FieldActorServicePrincipalID)
		}
		if _q.withResourceOwner != nil {
			_spec.Node.AddColumnOnce(resourceauthorizationevent.FieldResourceOwnerUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResourceAuthorizationEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(resourceauthorizationevent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = resourceauthorizationevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ResourceAuthorizationEventQuery) ForUpdate(opts ...sql.LockOption) *ResourceAuthorizationEventQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ResourceAuthorizationEventQuery) ForShare(opts ...sql.LockOption) *ResourceAuthorizationEventQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ResourceAuthorizationEventGroupBy is the group-by builder for ResourceAuthorizationEvent entities.
type ResourceAuthorizationEventGroupBy struct {
	selector
	build *ResourceAuthorizationEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResourceAuthorizationEventGroupBy) Aggregate(fns ...AggregateFunc) *ResourceAuthorizationEventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResourceAuthorizationEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceAuthorizationEventQuery, *ResourceAuthorizationEventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResourceAuthorizationEventGroupBy) sqlScan(ctx context.Context, root *ResourceAuthorizationEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResourceAuthorizationEventSelect is the builder for selecting fields of ResourceAuthorizationEvent entities.
type ResourceAuthorizationEventSelect struct {
	*ResourceAuthorizationEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResourceAuthorizationEventSelect) Aggregate(fns ...AggregateFunc) *ResourceAuthorizationEventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResourceAuthorizationEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceAuthorizationEventQuery, *ResourceAuthorizationEventSelect](ctx, _s.ResourceAuthorizationEventQuery, _s, _s.inters, v)
}

func (_s *ResourceAuthorizationEventSelect) sqlScan(ctx context.Context, root *ResourceAuthorizationEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
