// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resourceauthorizationevent"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResourceAuthorizationEventUpdate is the builder for updating ResourceAuthorizationEvent entities.
type ResourceAuthorizationEventUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceAuthorizationEventMutation
}

// Where appends a list predicates to the ResourceAuthorizationEventUpdate builder.
func (_u *ResourceAuthorizationEventUpdate) Where(ps ...predicate.ResourceAuthorizationEvent) *ResourceAuthorizationEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetAccountID(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableAccountID(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ResourceAuthorizationEventUpdate) ClearAccountID() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetGroupID(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableGroupID(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ResourceAuthorizationEventUpdate) ClearGroupID() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetActorUserID(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableActorUserID(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *ResourceAuthorizationEventUpdate) ClearActorUserID() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorServicePrincipalID sets the "actor_service_principal_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetActorServicePrincipalID(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetActorServicePrincipalID(v)
	return _u
}

// SetNillableActorServicePrincipalID sets the "actor_service_principal_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableActorServicePrincipalID(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetActorServicePrincipalID(*v)
	}
	return _u
}

// ClearActorServicePrincipalID clears the value of the "actor_service_principal_id" field.
func (_u *ResourceAuthorizationEventUpdate) ClearActorServicePrincipalID() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearActorServicePrincipalID()
	return _u
}

// SetResourceOwnerUserID sets the "resource_owner_user_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetResourceOwnerUserID(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetResourceOwnerUserID(v)
	return _u
}

// SetNillableResourceOwnerUserID sets the "resource_owner_user_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableResourceOwnerUserID(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetResourceOwnerUserID(*v)
	}
	return _u
}

// ClearResourceOwnerUserID clears the value of the "resource_owner_user_id" field.
func (_u *ResourceAuthorizationEventUpdate) ClearResourceOwnerUserID() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearResourceOwnerUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ResourceAuthorizationEventUpdate) SetEventType(v string) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableEventType(v *string) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceAccessVersion sets the "resource_access_version" field.
func (_u *ResourceAuthorizationEventUpdate) SetResourceAccessVersion(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.ResetResourceAccessVersion()
	_u.mutation.SetResourceAccessVersion(v)
	return _u
}

// SetNillableResourceAccessVersion sets the "resource_access_version" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableResourceAccessVersion(v *int64) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetResourceAccessVersion(*v)
	}
	return _u
}

// AddResourceAccessVersion adds value to the "resource_access_version" field.
func (_u *ResourceAuthorizationEventUpdate) AddResourceAccessVersion(v int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.AddResourceAccessVersion(v)
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *ResourceAuthorizationEventUpdate) SetAuthMethod(v string) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableAuthMethod(v *string) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ResourceAuthorizationEventUpdate) SetRequestID(v string) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableRequestID(v *string) *ResourceAuthorizationEventUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *ResourceAuthorizationEventUpdate) SetDetails(v map[string]interface{}) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ResourceAuthorizationEventUpdate) SetAccount(v *Account) *ResourceAuthorizationEventUpdate {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ResourceAuthorizationEventUpdate) SetGroup(v *Group) *ResourceAuthorizationEventUpdate {
	return _u.SetGroupID(v.ID)
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdate) SetActorUser(v *User) *ResourceAuthorizationEventUpdate {
	return _u.SetActorUserID(v.ID)
}

// SetActorServicePrincipal sets the "actor_service_principal" edge to the ServicePrincipal entity.
func (_u *ResourceAuthorizationEventUpdate) SetActorServicePrincipal(v *ServicePrincipal) *ResourceAuthorizationEventUpdate {
	return _u.SetActorServicePrincipalID(v.ID)
}

// SetResourceOwnerID sets the "resource_owner" edge to the User entity by ID.
func (_u *ResourceAuthorizationEventUpdate) SetResourceOwnerID(id int64) *ResourceAuthorizationEventUpdate {
	_u.mutation.SetResourceOwnerID(id)
	return _u
}

// SetNillableResourceOwnerID sets the "resource_owner" edge to the User entity by ID if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdate) SetNillableResourceOwnerID(id *int64) *ResourceAuthorizationEventUpdate {
	if id != nil {
		_u = _u.SetResourceOwnerID(*id)
	}
	return _u
}

// SetResourceOwner sets the "resource_owner" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdate) SetResourceOwner(v *User) *ResourceAuthorizationEventUpdate {
	return _u.SetResourceOwnerID(v.ID)
}

// Mutation returns the ResourceAuthorizationEventMutation object of the builder.
func (_u *ResourceAuthorizationEventUpdate) Mutation() *ResourceAuthorizationEventMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ResourceAuthorizationEventUpdate) ClearAccount() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ResourceAuthorizationEventUpdate) ClearGroup() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdate) ClearActorUser() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearActorUser()
	return _u
}

// ClearActorServicePrincipal clears the "actor_service_principal" edge to the ServicePrincipal entity.
func (_u *ResourceAuthorizationEventUpdate) ClearActorServicePrincipal() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearActorServicePrincipal()
	return _u
}

// ClearResourceOwner clears the "resource_owner" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdate) ClearResourceOwner() *ResourceAuthorizationEventUpdate {
	_u.mutation.ClearResourceOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceAuthorizationEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceAuthorizationEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceAuthorizationEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceAuthorizationEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceAuthorizationEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := resourceauthorizationevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := resourceauthorizationevent.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := resourceauthorizationevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceAuthorizationEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceauthorizationevent.Table, resourceauthorizationevent.Columns, sqlgraph.NewFieldSpec(resourceauthorizationevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(resourceauthorizationevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceAccessVersion(); ok {
		_spec.SetField(resourceauthorizationevent.FieldResourceAccessVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceAccessVersion(); ok {
		_spec.AddField(resourceauthorizationevent.FieldResourceAccessVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(resourceauthorizationevent.FieldAuthMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(resourceauthorizationevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(resourceauthorizationevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.AccountTable,
			Columns: []string{resourceauthorizationevent.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.AccountTable,
			Columns: []string{resourceauthorizationevent.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.GroupTable,
			Columns: []string{resourceauthorizationevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.GroupTable,
			Columns: []string{resourceauthorizationevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorUserTable,
			Columns: []string{resourceauthorizationevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorUserTable,
			Columns: []string{resourceauthorizationevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorServicePrincipalTable,
			Columns: []string{resourceauthorizationevent.ActorServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorServicePrincipalTable,
			Columns: []string{resourceauthorizationevent.ActorServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ResourceOwnerTable,
			Columns: []string{resourceauthorizationevent.ResourceOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ResourceOwnerTable,
			Columns: []string{resourceauthorizationevent.ResourceOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceauthorizationevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceAuthorizationEventUpdateOne is the builder for updating a single ResourceAuthorizationEvent entity.
type ResourceAuthorizationEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceAuthorizationEventMutation
}

// SetAccountID sets the "account_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetAccountID(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableAccountID(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) ClearAccountID() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetGroupID(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableGroupID(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) ClearGroupID() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetActorUserID(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableActorUserID(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) ClearActorUserID() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorServicePrincipalID sets the "actor_service_principal_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetActorServicePrincipalID(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetActorServicePrincipalID(v)
	return _u
}

// SetNillableActorServicePrincipalID sets the "actor_service_principal_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableActorServicePrincipalID(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetActorServicePrincipalID(*v)
	}
	return _u
}

// ClearActorServicePrincipalID clears the value of the "actor_service_principal_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) ClearActorServicePrincipalID() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearActorServicePrincipalID()
	return _u
}

// SetResourceOwnerUserID sets the "resource_owner_user_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetResourceOwnerUserID(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetResourceOwnerUserID(v)
	return _u
}

// SetNillableResourceOwnerUserID sets the "resource_owner_user_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableResourceOwnerUserID(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetResourceOwnerUserID(*v)
	}
	return _u
}

// ClearResourceOwnerUserID clears the value of the "resource_owner_user_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) ClearResourceOwnerUserID() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearResourceOwnerUserID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetEventType(v string) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableEventType(v *string) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetResourceAccessVersion sets the "resource_access_version" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetResourceAccessVersion(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ResetResourceAccessVersion()
	_u.mutation.SetResourceAccessVersion(v)
	return _u
}

// SetNillableResourceAccessVersion sets the "resource_access_version" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableResourceAccessVersion(v *int64) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetResourceAccessVersion(*v)
	}
	return _u
}

// AddResourceAccessVersion adds value to the "resource_access_version" field.
func (_u *ResourceAuthorizationEventUpdateOne) AddResourceAccessVersion(v int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.AddResourceAccessVersion(v)
	return _u
}

// SetAuthMethod sets the "auth_method" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetAuthMethod(v string) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetAuthMethod(v)
	return _u
}

// SetNillableAuthMethod sets the "auth_method" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableAuthMethod(v *string) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetAuthMethod(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetRequestID(v string) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableRequestID(v *string) *ResourceAuthorizationEventUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *ResourceAuthorizationEventUpdateOne) SetDetails(v map[string]interface{}) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ResourceAuthorizationEventUpdateOne) SetAccount(v *Account) *ResourceAuthorizationEventUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ResourceAuthorizationEventUpdateOne) SetGroup(v *Group) *ResourceAuthorizationEventUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdateOne) SetActorUser(v *User) *ResourceAuthorizationEventUpdateOne {
	return _u.SetActorUserID(v.ID)
}

// SetActorServicePrincipal sets the "actor_service_principal" edge to the ServicePrincipal entity.
func (_u *ResourceAuthorizationEventUpdateOne) SetActorServicePrincipal(v *ServicePrincipal) *ResourceAuthorizationEventUpdateOne {
	return _u.SetActorServicePrincipalID(v.ID)
}

// SetResourceOwnerID sets the "resource_owner" edge to the User entity by ID.
func (_u *ResourceAuthorizationEventUpdateOne) SetResourceOwnerID(id int64) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.SetResourceOwnerID(id)
	return _u
}

// SetNillableResourceOwnerID sets the "resource_owner" edge to the User entity by ID if the given value is not nil.
func (_u *ResourceAuthorizationEventUpdateOne) SetNillableResourceOwnerID(id *int64) *ResourceAuthorizationEventUpdateOne {
	if id != nil {
		_u = _u.SetResourceOwnerID(*id)
	}
	return _u
}

// SetResourceOwner sets the "resource_owner" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdateOne) SetResourceOwner(v *User) *ResourceAuthorizationEventUpdateOne {
	return _u.SetResourceOwnerID(v.ID)
}

// Mutation returns the ResourceAuthorizationEventMutation object of the builder.
func (_u *ResourceAuthorizationEventUpdateOne) Mutation() *ResourceAuthorizationEventMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ResourceAuthorizationEventUpdateOne) ClearAccount() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ResourceAuthorizationEventUpdateOne) ClearGroup() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdateOne) ClearActorUser() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearActorUser()
	return _u
}

// ClearActorServicePrincipal clears the "actor_service_principal" edge to the ServicePrincipal entity.
func (_u *ResourceAuthorizationEventUpdateOne) ClearActorServicePrincipal() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearActorServicePrincipal()
	return _u
}

// ClearResourceOwner clears the "resource_owner" edge to the User entity.
func (_u *ResourceAuthorizationEventUpdateOne) ClearResourceOwner() *ResourceAuthorizationEventUpdateOne {
	_u.mutation.ClearResourceOwner()
	return _u
}

// Where appends a list predicates to the ResourceAuthorizationEventUpdate builder.
func (_u *ResourceAuthorizationEventUpdateOne) Where(ps ...predicate.ResourceAuthorizationEvent) *ResourceAuthorizationEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceAuthorizationEventUpdateOne) Select(field string, fields ...string) *ResourceAuthorizationEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResourceAuthorizationEvent entity.
func (_u *ResourceAuthorizationEventUpdateOne) Save(ctx context.Context) (*ResourceAuthorizationEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceAuthorizationEventUpdateOne) SaveX(ctx context.Context) *ResourceAuthorizationEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceAuthorizationEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceAuthorizationEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceAuthorizationEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := resourceauthorizationevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMethod(); ok {
		if err := resourceauthorizationevent.AuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "auth_method", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := resourceauthorizationevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ResourceAuthorizationEvent.request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceAuthorizationEventUpdateOne) sqlSave(ctx context.Context) (_node *ResourceAuthorizationEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceauthorizationevent.Table, resourceauthorizationevent.Columns, sqlgraph.NewFieldSpec(resourceauthorizationevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceAuthorizationEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceauthorizationevent.FieldID)
		for _, f := range fields {
			if !resourceauthorizationevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourceauthorizationevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(resourceauthorizationevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceAccessVersion(); ok {
		_spec.SetField(resourceauthorizationevent.FieldResourceAccessVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceAccessVersion(); ok {
		_spec.AddField(resourceauthorizationevent.FieldResourceAccessVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthMethod(); ok {
		_spec.SetField(resourceauthorizationevent.FieldAuthMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(resourceauthorizationevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(resourceauthorizationevent.FieldDetails, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.AccountTable,
			Columns: []string{resourceauthorizationevent.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.AccountTable,
			Columns: []string{resourceauthorizationevent.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.GroupTable,
			Columns: []string{resourceauthorizationevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.GroupTable,
			Columns: []string{resourceauthorizationevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorUserTable,
			Columns: []string{resourceauthorizationevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorUserTable,
			Columns: []string{resourceauthorizationevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorServicePrincipalTable,
			Columns: []string{resourceauthorizationevent.ActorServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ActorServicePrincipalTable,
			Columns: []string{resourceauthorizationevent.ActorServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceOwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ResourceOwnerTable,
			Columns: []string{resourceauthorizationevent.ResourceOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceOwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceauthorizationevent.ResourceOwnerTable,
			Columns: []string{resourceauthorizationevent.ResourceOwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResourceAuthorizationEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceauthorizationevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
