// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
)

// ServicePrincipal is the model entity for the ServicePrincipal schema.
type ServicePrincipal struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AuthzVersion holds the value of the "authz_version" field.
	AuthzVersion int64 `json:"authz_version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServicePrincipalQuery when eager-loading is set.
	Edges        ServicePrincipalEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServicePrincipalEdges holds the relations/edges for other nodes in the graph.
type ServicePrincipalEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// WorkerPermissions holds the value of the worker_permissions edge.
	WorkerPermissions []*Permission `json:"worker_permissions,omitempty"`
	// ServicePrincipalRoles holds the value of the service_principal_roles edge.
	ServicePrincipalRoles []*ServicePrincipalRole `json:"service_principal_roles,omitempty"`
	// WorkerPermissionGrants holds the value of the worker_permission_grants edge.
	WorkerPermissionGrants []*ServicePrincipalWorkerPermission `json:"worker_permission_grants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e ServicePrincipalEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// WorkerPermissionsOrErr returns the WorkerPermissions value or an error if the edge
// was not loaded in eager-loading.
func (e ServicePrincipalEdges) WorkerPermissionsOrErr() ([]*Permission, error) {
	if e.loadedTypes[1] {
		return e.WorkerPermissions, nil
	}
	return nil, &NotLoadedError{edge: "worker_permissions"}
}

// ServicePrincipalRolesOrErr returns the ServicePrincipalRoles value or an error if the edge
// was not loaded in eager-loading.
func (e ServicePrincipalEdges) ServicePrincipalRolesOrErr() ([]*ServicePrincipalRole, error) {
	if e.loadedTypes[2] {
		return e.ServicePrincipalRoles, nil
	}
	return nil, &NotLoadedError{edge: "service_principal_roles"}
}

// WorkerPermissionGrantsOrErr returns the WorkerPermissionGrants value or an error if the edge
// was not loaded in eager-loading.
func (e ServicePrincipalEdges) WorkerPermissionGrantsOrErr() ([]*ServicePrincipalWorkerPermission, error) {
	if e.loadedTypes[3] {
		return e.WorkerPermissionGrants, nil
	}
	return nil, &NotLoadedError{edge: "worker_permission_grants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServicePrincipal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceprincipal.FieldID, serviceprincipal.FieldAuthzVersion:
			values[i] = new(sql.NullInt64)
		case serviceprincipal.FieldCode, serviceprincipal.FieldName, serviceprincipal.FieldStatus:
			values[i] = new(sql.NullString)
		case serviceprincipal.FieldCreatedAt, serviceprincipal.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServicePrincipal fields.
func (_m *ServicePrincipal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceprincipal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case serviceprincipal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case serviceprincipal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case serviceprincipal.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case serviceprincipal.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case serviceprincipal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case serviceprincipal.FieldAuthzVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field authz_version", values[i])
			} else if value.Valid {
				_m.AuthzVersion = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServicePrincipal.
// This includes values selected through modifiers, order, etc.
func (_m *ServicePrincipal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryRoles() *RoleQuery {
	return NewServicePrincipalClient(_m.config).QueryRoles(_m)
}

// QueryWorkerPermissions queries the "worker_permissions" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryWorkerPermissions() *PermissionQuery {
	return NewServicePrincipalClient(_m.config).QueryWorkerPermissions(_m)
}

// QueryServicePrincipalRoles queries the "service_principal_roles" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryServicePrincipalRoles() *ServicePrincipalRoleQuery {
	return NewServicePrincipalClient(_m.config).QueryServicePrincipalRoles(_m)
}

// QueryWorkerPermissionGrants queries the "worker_permission_grants" edge of the ServicePrincipal entity.
func (_m *ServicePrincipal) QueryWorkerPermissionGrants() *ServicePrincipalWorkerPermissionQuery {
	return NewServicePrincipalClient(_m.config).QueryWorkerPermissionGrants(_m)
}

// Update returns a builder for updating this ServicePrincipal.
// Note that you need to call ServicePrincipal.Unwrap() before calling this method if this ServicePrincipal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServicePrincipal) Update() *ServicePrincipalUpdateOne {
	return NewServicePrincipalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServicePrincipal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServicePrincipal) Unwrap() *ServicePrincipal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServicePrincipal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServicePrincipal) String() string {
	var builder strings.Builder
	builder.WriteString("ServicePrincipal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("authz_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthzVersion))
	builder.WriteByte(')')
	return builder.String()
}

// ServicePrincipals is a parsable slice of ServicePrincipal.
type ServicePrincipals []*ServicePrincipal
