// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipalrole"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ServicePrincipalRoleUpdate is the builder for updating ServicePrincipalRole entities.
type ServicePrincipalRoleUpdate struct {
	config
	hooks    []Hook
	mutation *ServicePrincipalRoleMutation
}

// Where appends a list predicates to the ServicePrincipalRoleUpdate builder.
func (_u *ServicePrincipalRoleUpdate) Where(ps ...predicate.ServicePrincipalRole) *ServicePrincipalRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServicePrincipalRoleUpdate) SetUpdatedAt(v time.Time) *ServicePrincipalRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServicePrincipalID sets the "service_principal_id" field.
func (_u *ServicePrincipalRoleUpdate) SetServicePrincipalID(v int64) *ServicePrincipalRoleUpdate {
	_u.mutation.SetServicePrincipalID(v)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdate) SetNillableServicePrincipalID(v *int64) *ServicePrincipalRoleUpdate {
	if v != nil {
		_u.SetServicePrincipalID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *ServicePrincipalRoleUpdate) SetRoleID(v int64) *ServicePrincipalRoleUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdate) SetNillableRoleID(v *int64) *ServicePrincipalRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_u *ServicePrincipalRoleUpdate) SetGrantedByUserID(v int64) *ServicePrincipalRoleUpdate {
	_u.mutation.SetGrantedByUserID(v)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdate) SetNillableGrantedByUserID(v *int64) *ServicePrincipalRoleUpdate {
	if v != nil {
		_u.SetGrantedByUserID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ServicePrincipalRoleUpdate) SetExpiresAt(v time.Time) *ServicePrincipalRoleUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdate) SetNillableExpiresAt(v *time.Time) *ServicePrincipalRoleUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ServicePrincipalRoleUpdate) ClearExpiresAt() *ServicePrincipalRoleUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalRoleUpdate) SetServicePrincipal(v *ServicePrincipal) *ServicePrincipalRoleUpdate {
	return _u.SetServicePrincipalID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *ServicePrincipalRoleUpdate) SetRole(v *Role) *ServicePrincipalRoleUpdate {
	return _u.SetRoleID(v.ID)
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_u *ServicePrincipalRoleUpdate) SetGrantedByUser(v *User) *ServicePrincipalRoleUpdate {
	return _u.SetGrantedByUserID(v.ID)
}

// Mutation returns the ServicePrincipalRoleMutation object of the builder.
func (_u *ServicePrincipalRoleUpdate) Mutation() *ServicePrincipalRoleMutation {
	return _u.mutation
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalRoleUpdate) ClearServicePrincipal() *ServicePrincipalRoleUpdate {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *ServicePrincipalRoleUpdate) ClearRole() *ServicePrincipalRoleUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearGrantedByUser clears the "granted_by_user" edge to the User entity.
func (_u *ServicePrincipalRoleUpdate) ClearGrantedByUser() *ServicePrincipalRoleUpdate {
	_u.mutation.ClearGrantedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServicePrincipalRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServicePrincipalRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServicePrincipalRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceprincipalrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalRoleUpdate) check() error {
	if _u.mutation.ServicePrincipalCleared() && len(_u.mutation.ServicePrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.service_principal"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.role"`)
	}
	if _u.mutation.GrantedByUserCleared() && len(_u.mutation.GrantedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.granted_by_user"`)
	}
	return nil
}

func (_u *ServicePrincipalRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipalrole.Table, serviceprincipalrole.Columns, sqlgraph.NewFieldSpec(serviceprincipalrole.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprincipalrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(serviceprincipalrole.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(serviceprincipalrole.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.ServicePrincipalTable,
			Columns: []string{serviceprincipalrole.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.ServicePrincipalTable,
			Columns: []string{serviceprincipalrole.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.RoleTable,
			Columns: []string{serviceprincipalrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.RoleTable,
			Columns: []string{serviceprincipalrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.GrantedByUserTable,
			Columns: []string{serviceprincipalrole.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.GrantedByUserTable,
			Columns: []string{serviceprincipalrole.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipalrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServicePrincipalRoleUpdateOne is the builder for updating a single ServicePrincipalRole entity.
type ServicePrincipalRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServicePrincipalRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServicePrincipalRoleUpdateOne) SetUpdatedAt(v time.Time) *ServicePrincipalRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServicePrincipalID sets the "service_principal_id" field.
func (_u *ServicePrincipalRoleUpdateOne) SetServicePrincipalID(v int64) *ServicePrincipalRoleUpdateOne {
	_u.mutation.SetServicePrincipalID(v)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdateOne) SetNillableServicePrincipalID(v *int64) *ServicePrincipalRoleUpdateOne {
	if v != nil {
		_u.SetServicePrincipalID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *ServicePrincipalRoleUpdateOne) SetRoleID(v int64) *ServicePrincipalRoleUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdateOne) SetNillableRoleID(v *int64) *ServicePrincipalRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetGrantedByUserID sets the "granted_by_user_id" field.
func (_u *ServicePrincipalRoleUpdateOne) SetGrantedByUserID(v int64) *ServicePrincipalRoleUpdateOne {
	_u.mutation.SetGrantedByUserID(v)
	return _u
}

// SetNillableGrantedByUserID sets the "granted_by_user_id" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdateOne) SetNillableGrantedByUserID(v *int64) *ServicePrincipalRoleUpdateOne {
	if v != nil {
		_u.SetGrantedByUserID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ServicePrincipalRoleUpdateOne) SetExpiresAt(v time.Time) *ServicePrincipalRoleUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ServicePrincipalRoleUpdateOne) SetNillableExpiresAt(v *time.Time) *ServicePrincipalRoleUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ServicePrincipalRoleUpdateOne) ClearExpiresAt() *ServicePrincipalRoleUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalRoleUpdateOne) SetServicePrincipal(v *ServicePrincipal) *ServicePrincipalRoleUpdateOne {
	return _u.SetServicePrincipalID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *ServicePrincipalRoleUpdateOne) SetRole(v *Role) *ServicePrincipalRoleUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetGrantedByUser sets the "granted_by_user" edge to the User entity.
func (_u *ServicePrincipalRoleUpdateOne) SetGrantedByUser(v *User) *ServicePrincipalRoleUpdateOne {
	return _u.SetGrantedByUserID(v.ID)
}

// Mutation returns the ServicePrincipalRoleMutation object of the builder.
func (_u *ServicePrincipalRoleUpdateOne) Mutation() *ServicePrincipalRoleMutation {
	return _u.mutation
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalRoleUpdateOne) ClearServicePrincipal() *ServicePrincipalRoleUpdateOne {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *ServicePrincipalRoleUpdateOne) ClearRole() *ServicePrincipalRoleUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearGrantedByUser clears the "granted_by_user" edge to the User entity.
func (_u *ServicePrincipalRoleUpdateOne) ClearGrantedByUser() *ServicePrincipalRoleUpdateOne {
	_u.mutation.ClearGrantedByUser()
	return _u
}

// Where appends a list predicates to the ServicePrincipalRoleUpdate builder.
func (_u *ServicePrincipalRoleUpdateOne) Where(ps ...predicate.ServicePrincipalRole) *ServicePrincipalRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServicePrincipalRoleUpdateOne) Select(field string, fields ...string) *ServicePrincipalRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServicePrincipalRole entity.
func (_u *ServicePrincipalRoleUpdateOne) Save(ctx context.Context) (*ServicePrincipalRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalRoleUpdateOne) SaveX(ctx context.Context) *ServicePrincipalRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServicePrincipalRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServicePrincipalRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceprincipalrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalRoleUpdateOne) check() error {
	if _u.mutation.ServicePrincipalCleared() && len(_u.mutation.ServicePrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.service_principal"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.role"`)
	}
	if _u.mutation.GrantedByUserCleared() && len(_u.mutation.GrantedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalRole.granted_by_user"`)
	}
	return nil
}

func (_u *ServicePrincipalRoleUpdateOne) sqlSave(ctx context.Context) (_node *ServicePrincipalRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipalrole.Table, serviceprincipalrole.Columns, sqlgraph.NewFieldSpec(serviceprincipalrole.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServicePrincipalRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceprincipalrole.FieldID)
		for _, f := range fields {
			if !serviceprincipalrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serviceprincipalrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceprincipalrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(serviceprincipalrole.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(serviceprincipalrole.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.ServicePrincipalTable,
			Columns: []string{serviceprincipalrole.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.ServicePrincipalTable,
			Columns: []string{serviceprincipalrole.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.RoleTable,
			Columns: []string{serviceprincipalrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.RoleTable,
			Columns: []string{serviceprincipalrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.GrantedByUserTable,
			Columns: []string{serviceprincipalrole.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalrole.GrantedByUserTable,
			Columns: []string{serviceprincipalrole.GrantedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServicePrincipalRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipalrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
