// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/permission"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipalworkerpermission"
)

// ServicePrincipalWorkerPermission is the model entity for the ServicePrincipalWorkerPermission schema.
type ServicePrincipalWorkerPermission struct {
	config `json:"-"`
	// ServicePrincipalID holds the value of the "service_principal_id" field.
	ServicePrincipalID int64 `json:"service_principal_id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID int64 `json:"permission_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServicePrincipalWorkerPermissionQuery when eager-loading is set.
	Edges        ServicePrincipalWorkerPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServicePrincipalWorkerPermissionEdges holds the relations/edges for other nodes in the graph.
type ServicePrincipalWorkerPermissionEdges struct {
	// ServicePrincipal holds the value of the service_principal edge.
	ServicePrincipal *ServicePrincipal `json:"service_principal,omitempty"`
	// Permission holds the value of the permission edge.
	Permission *Permission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ServicePrincipalOrErr returns the ServicePrincipal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalWorkerPermissionEdges) ServicePrincipalOrErr() (*ServicePrincipal, error) {
	if e.ServicePrincipal != nil {
		return e.ServicePrincipal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: serviceprincipal.Label}
	}
	return nil, &NotLoadedError{edge: "service_principal"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalWorkerPermissionEdges) PermissionOrErr() (*Permission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: permission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServicePrincipalWorkerPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceprincipalworkerpermission.FieldServicePrincipalID, serviceprincipalworkerpermission.FieldPermissionID:
			values[i] = new(sql.NullInt64)
		case serviceprincipalworkerpermission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServicePrincipalWorkerPermission fields.
func (_m *ServicePrincipalWorkerPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceprincipalworkerpermission.FieldServicePrincipalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field service_principal_id", values[i])
			} else if value.Valid {
				_m.ServicePrincipalID = value.Int64
			}
		case serviceprincipalworkerpermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = value.Int64
			}
		case serviceprincipalworkerpermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServicePrincipalWorkerPermission.
// This includes values selected through modifiers, order, etc.
func (_m *ServicePrincipalWorkerPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServicePrincipal queries the "service_principal" edge of the ServicePrincipalWorkerPermission entity.
func (_m *ServicePrincipalWorkerPermission) QueryServicePrincipal() *ServicePrincipalQuery {
	return NewServicePrincipalWorkerPermissionClient(_m.config).QueryServicePrincipal(_m)
}

// QueryPermission queries the "permission" edge of the ServicePrincipalWorkerPermission entity.
func (_m *ServicePrincipalWorkerPermission) QueryPermission() *PermissionQuery {
	return NewServicePrincipalWorkerPermissionClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this ServicePrincipalWorkerPermission.
// Note that you need to call ServicePrincipalWorkerPermission.Unwrap() before calling this method if this ServicePrincipalWorkerPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServicePrincipalWorkerPermission) Update() *ServicePrincipalWorkerPermissionUpdateOne {
	return NewServicePrincipalWorkerPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServicePrincipalWorkerPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServicePrincipalWorkerPermission) Unwrap() *ServicePrincipalWorkerPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServicePrincipalWorkerPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServicePrincipalWorkerPermission) String() string {
	var builder strings.Builder
	builder.WriteString("ServicePrincipalWorkerPermission(")
	builder.WriteString("service_principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServicePrincipalID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ServicePrincipalWorkerPermissions is a parsable slice of ServicePrincipalWorkerPermission.
type ServicePrincipalWorkerPermissions []*ServicePrincipalWorkerPermission
