// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipalrole"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ServicePrincipalRoleQuery is the builder for querying ServicePrincipalRole entities.
type ServicePrincipalRoleQuery struct {
	config
	ctx                  *QueryContext
	order                []serviceprincipalrole.OrderOption
	inters               []Interceptor
	predicates           []predicate.ServicePrincipalRole
	withServicePrincipal *ServicePrincipalQuery
	withRole             *RoleQuery
	withGrantedByUser    *UserQuery
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServicePrincipalRoleQuery builder.
func (_q *ServicePrincipalRoleQuery) Where(ps ...predicate.ServicePrincipalRole) *ServicePrincipalRoleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ServicePrincipalRoleQuery) Limit(limit int) *ServicePrincipalRoleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ServicePrincipalRoleQuery) Offset(offset int) *ServicePrincipalRoleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ServicePrincipalRoleQuery) Unique(unique bool) *ServicePrincipalRoleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ServicePrincipalRoleQuery) Order(o ...serviceprincipalrole.OrderOption) *ServicePrincipalRoleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryServicePrincipal chains the current query on the "service_principal" edge.
func (_q *ServicePrincipalRoleQuery) QueryServicePrincipal() *ServicePrincipalQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceprincipalrole.Table, serviceprincipalrole.FieldID, selector),
			sqlgraph.To(serviceprincipal.Table, serviceprincipal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, serviceprincipalrole.ServicePrincipalTable, serviceprincipalrole.ServicePrincipalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRole chains the current query on the "role" edge.
func (_q *ServicePrincipalRoleQuery) QueryRole() *RoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceprincipalrole.Table, serviceprincipalrole.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, serviceprincipalrole.RoleTable, serviceprincipalrole.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrantedByUser chains the current query on the "granted_by_user" edge.
func (_q *ServicePrincipalRoleQuery) QueryGrantedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceprincipalrole.Table, serviceprincipalrole.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, serviceprincipalrole.GrantedByUserTable, serviceprincipalrole.GrantedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServicePrincipalRole entity from the query.
// Returns a *NotFoundError when no ServicePrincipalRole was found.
func (_q *ServicePrincipalRoleQuery) First(ctx context.Context) (*ServicePrincipalRole, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serviceprincipalrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) FirstX(ctx context.Context) *ServicePrincipalRole {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServicePrincipalRole ID from the query.
// Returns a *NotFoundError when no ServicePrincipalRole ID was found.
func (_q *ServicePrincipalRoleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serviceprincipalrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServicePrincipalRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServicePrincipalRole entity is found.
// Returns a *NotFoundError when no ServicePrincipalRole entities are found.
func (_q *ServicePrincipalRoleQuery) Only(ctx context.Context) (*ServicePrincipalRole, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serviceprincipalrole.Label}
	default:
		return nil, &NotSingularError{serviceprincipalrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) OnlyX(ctx context.Context) *ServicePrincipalRole {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServicePrincipalRole ID in the query.
// Returns a *NotSingularError when more than one ServicePrincipalRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ServicePrincipalRoleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serviceprincipalrole.Label}
	default:
		err = &NotSingularError{serviceprincipalrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServicePrincipalRoles.
func (_q *ServicePrincipalRoleQuery) All(ctx context.Context) ([]*ServicePrincipalRole, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServicePrincipalRole, *ServicePrincipalRoleQuery]()
	return withInterceptors[[]*ServicePrincipalRole](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) AllX(ctx context.Context) []*ServicePrincipalRole {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServicePrincipalRole IDs.
func (_q *ServicePrincipalRoleQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(serviceprincipalrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ServicePrincipalRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ServicePrincipalRoleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ServicePrincipalRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ServicePrincipalRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServicePrincipalRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ServicePrincipalRoleQuery) Clone() *ServicePrincipalRoleQuery {
	if _q == nil {
		return nil
	}
	return &ServicePrincipalRoleQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]serviceprincipalrole.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.ServicePrincipalRole{}, _q.predicates...),
		withServicePrincipal: _q.withServicePrincipal.Clone(),
		withRole:             _q.withRole.Clone(),
		withGrantedByUser:    _q.withGrantedByUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithServicePrincipal tells the query-builder to eager-load the nodes that are connected to
// the "service_principal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ServicePrincipalRoleQuery) WithServicePrincipal(opts ...func(*ServicePrincipalQuery)) *ServicePrincipalRoleQuery {
	query := (&ServicePrincipalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServicePrincipal = query
	return _q
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ServicePrincipalRoleQuery) WithRole(opts ...func(*RoleQuery)) *ServicePrincipalRoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRole = query
	return _q
}

// WithGrantedByUser tells the query-builder to eager-load the nodes that are connected to
// the "granted_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ServicePrincipalRoleQuery) WithGrantedByUser(opts ...func(*UserQuery)) *ServicePrincipalRoleQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrantedByUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServicePrincipalRole.Query().
//		GroupBy(serviceprincipalrole.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ServicePrincipalRoleQuery) GroupBy(field string, fields ...string) *ServicePrincipalRoleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServicePrincipalRoleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = serviceprincipalrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ServicePrincipalRole.Query().
//		Select(serviceprincipalrole.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ServicePrincipalRoleQuery) Select(fields ...string) *ServicePrincipalRoleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ServicePrincipalRoleSelect{ServicePrincipalRoleQuery: _q}
	sbuild.label = serviceprincipalrole.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServicePrincipalRoleSelect configured with the given aggregations.
func (_q *ServicePrincipalRoleQuery) Aggregate(fns ...AggregateFunc) *ServicePrincipalRoleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ServicePrincipalRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !serviceprincipalrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ServicePrincipalRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServicePrincipalRole, error) {
	var (
		nodes       = []*ServicePrincipalRole{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withServicePrincipal != nil,
			_q.withRole != nil,
			_q.withGrantedByUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServicePrincipalRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServicePrincipalRole{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withServicePrincipal; query != nil {
		if err := _q.loadServicePrincipal(ctx, query, nodes, nil,
			func(n *ServicePrincipalRole, e *ServicePrincipal) { n.Edges.ServicePrincipal = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRole; query != nil {
		if err := _q.loadRole(ctx, query, nodes, nil,
			func(n *ServicePrincipalRole, e *Role) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrantedByUser; query != nil {
		if err := _q.loadGrantedByUser(ctx, query, nodes, nil,
			func(n *ServicePrincipalRole, e *User) { n.Edges.GrantedByUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ServicePrincipalRoleQuery) loadServicePrincipal(ctx context.Context, query *ServicePrincipalQuery, nodes []*ServicePrincipalRole, init func(*ServicePrincipalRole), assign func(*ServicePrincipalRole, *ServicePrincipal)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ServicePrincipalRole)
	for i := range nodes {
		fk := nodes[i].ServicePrincipalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(serviceprincipal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_principal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ServicePrincipalRoleQuery) loadRole(ctx context.Context, query *RoleQuery, nodes []*ServicePrincipalRole, init func(*ServicePrincipalRole), assign func(*ServicePrincipalRole, *Role)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ServicePrincipalRole)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ServicePrincipalRoleQuery) loadGrantedByUser(ctx context.Context, query *UserQuery, nodes []*ServicePrincipalRole, init func(*ServicePrincipalRole), assign func(*ServicePrincipalRole, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ServicePrincipalRole)
	for i := range nodes {
		fk := nodes[i].GrantedByUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "granted_by_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ServicePrincipalRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ServicePrincipalRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serviceprincipalrole.Table, serviceprincipalrole.Columns, sqlgraph.NewFieldSpec(serviceprincipalrole.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceprincipalrole.FieldID)
		for i := range fields {
			if fields[i] != serviceprincipalrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withServicePrincipal != nil {
			_spec.Node.AddColumnOnce(serviceprincipalrole.FieldServicePrincipalID)
		}
		if _q.withRole != nil {
			_spec.Node.AddColumnOnce(serviceprincipalrole.FieldRoleID)
		}
		if _q.withGrantedByUser != nil {
			_spec.Node.AddColumnOnce(serviceprincipalrole.FieldGrantedByUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ServicePrincipalRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(serviceprincipalrole.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = serviceprincipalrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ServicePrincipalRoleQuery) ForUpdate(opts ...sql.LockOption) *ServicePrincipalRoleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ServicePrincipalRoleQuery) ForShare(opts ...sql.LockOption) *ServicePrincipalRoleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ServicePrincipalRoleGroupBy is the group-by builder for ServicePrincipalRole entities.
type ServicePrincipalRoleGroupBy struct {
	selector
	build *ServicePrincipalRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ServicePrincipalRoleGroupBy) Aggregate(fns ...AggregateFunc) *ServicePrincipalRoleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ServicePrincipalRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServicePrincipalRoleQuery, *ServicePrincipalRoleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ServicePrincipalRoleGroupBy) sqlScan(ctx context.Context, root *ServicePrincipalRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServicePrincipalRoleSelect is the builder for selecting fields of ServicePrincipalRole entities.
type ServicePrincipalRoleSelect struct {
	*ServicePrincipalRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ServicePrincipalRoleSelect) Aggregate(fns ...AggregateFunc) *ServicePrincipalRoleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ServicePrincipalRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServicePrincipalRoleQuery, *ServicePrincipalRoleSelect](ctx, _s.ServicePrincipalRoleQuery, _s, _s.inters, v)
}

func (_s *ServicePrincipalRoleSelect) sqlScan(ctx context.Context, root *ServicePrincipalRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
