// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipalrole"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ServicePrincipalRole is the model entity for the ServicePrincipalRole schema.
type ServicePrincipalRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ServicePrincipalID holds the value of the "service_principal_id" field.
	ServicePrincipalID int64 `json:"service_principal_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID int64 `json:"role_id,omitempty"`
	// GrantedByUserID holds the value of the "granted_by_user_id" field.
	GrantedByUserID int64 `json:"granted_by_user_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServicePrincipalRoleQuery when eager-loading is set.
	Edges        ServicePrincipalRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ServicePrincipalRoleEdges holds the relations/edges for other nodes in the graph.
type ServicePrincipalRoleEdges struct {
	// ServicePrincipal holds the value of the service_principal edge.
	ServicePrincipal *ServicePrincipal `json:"service_principal,omitempty"`
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// GrantedByUser holds the value of the granted_by_user edge.
	GrantedByUser *User `json:"granted_by_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ServicePrincipalOrErr returns the ServicePrincipal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalRoleEdges) ServicePrincipalOrErr() (*ServicePrincipal, error) {
	if e.ServicePrincipal != nil {
		return e.ServicePrincipal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: serviceprincipal.Label}
	}
	return nil, &NotLoadedError{edge: "service_principal"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalRoleEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// GrantedByUserOrErr returns the GrantedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServicePrincipalRoleEdges) GrantedByUserOrErr() (*User, error) {
	if e.GrantedByUser != nil {
		return e.GrantedByUser, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "granted_by_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServicePrincipalRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case serviceprincipalrole.FieldID, serviceprincipalrole.FieldServicePrincipalID, serviceprincipalrole.FieldRoleID, serviceprincipalrole.FieldGrantedByUserID:
			values[i] = new(sql.NullInt64)
		case serviceprincipalrole.FieldCreatedAt, serviceprincipalrole.FieldUpdatedAt, serviceprincipalrole.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServicePrincipalRole fields.
func (_m *ServicePrincipalRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case serviceprincipalrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case serviceprincipalrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case serviceprincipalrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case serviceprincipalrole.FieldServicePrincipalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field service_principal_id", values[i])
			} else if value.Valid {
				_m.ServicePrincipalID = value.Int64
			}
		case serviceprincipalrole.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.Int64
			}
		case serviceprincipalrole.FieldGrantedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_by_user_id", values[i])
			} else if value.Valid {
				_m.GrantedByUserID = value.Int64
			}
		case serviceprincipalrole.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServicePrincipalRole.
// This includes values selected through modifiers, order, etc.
func (_m *ServicePrincipalRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryServicePrincipal queries the "service_principal" edge of the ServicePrincipalRole entity.
func (_m *ServicePrincipalRole) QueryServicePrincipal() *ServicePrincipalQuery {
	return NewServicePrincipalRoleClient(_m.config).QueryServicePrincipal(_m)
}

// QueryRole queries the "role" edge of the ServicePrincipalRole entity.
func (_m *ServicePrincipalRole) QueryRole() *RoleQuery {
	return NewServicePrincipalRoleClient(_m.config).QueryRole(_m)
}

// QueryGrantedByUser queries the "granted_by_user" edge of the ServicePrincipalRole entity.
func (_m *ServicePrincipalRole) QueryGrantedByUser() *UserQuery {
	return NewServicePrincipalRoleClient(_m.config).QueryGrantedByUser(_m)
}

// Update returns a builder for updating this ServicePrincipalRole.
// Note that you need to call ServicePrincipalRole.Unwrap() before calling this method if this ServicePrincipalRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServicePrincipalRole) Update() *ServicePrincipalRoleUpdateOne {
	return NewServicePrincipalRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServicePrincipalRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServicePrincipalRole) Unwrap() *ServicePrincipalRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServicePrincipalRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServicePrincipalRole) String() string {
	var builder strings.Builder
	builder.WriteString("ServicePrincipalRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("service_principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServicePrincipalID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("granted_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantedByUserID))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ServicePrincipalRoles is a parsable slice of ServicePrincipalRole.
type ServicePrincipalRoles []*ServicePrincipalRole
