// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/permission"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipal"
	"github.com/Wei-Shaw/sub2api/ent/serviceprincipalworkerpermission"
)

// ServicePrincipalWorkerPermissionUpdate is the builder for updating ServicePrincipalWorkerPermission entities.
type ServicePrincipalWorkerPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *ServicePrincipalWorkerPermissionMutation
}

// Where appends a list predicates to the ServicePrincipalWorkerPermissionUpdate builder.
func (_u *ServicePrincipalWorkerPermissionUpdate) Where(ps ...predicate.ServicePrincipalWorkerPermission) *ServicePrincipalWorkerPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServicePrincipalID sets the "service_principal_id" field.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetServicePrincipalID(v int64) *ServicePrincipalWorkerPermissionUpdate {
	_u.mutation.SetServicePrincipalID(v)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal_id" field if the given value is not nil.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetNillableServicePrincipalID(v *int64) *ServicePrincipalWorkerPermissionUpdate {
	if v != nil {
		_u.SetServicePrincipalID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetPermissionID(v int64) *ServicePrincipalWorkerPermissionUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetNillablePermissionID(v *int64) *ServicePrincipalWorkerPermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetServicePrincipal(v *ServicePrincipal) *ServicePrincipalWorkerPermissionUpdate {
	return _u.SetServicePrincipalID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_u *ServicePrincipalWorkerPermissionUpdate) SetPermission(v *Permission) *ServicePrincipalWorkerPermissionUpdate {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the ServicePrincipalWorkerPermissionMutation object of the builder.
func (_u *ServicePrincipalWorkerPermissionUpdate) Mutation() *ServicePrincipalWorkerPermissionMutation {
	return _u.mutation
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalWorkerPermissionUpdate) ClearServicePrincipal() *ServicePrincipalWorkerPermissionUpdate {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearPermission clears the "permission" edge to the Permission entity.
func (_u *ServicePrincipalWorkerPermissionUpdate) ClearPermission() *ServicePrincipalWorkerPermissionUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServicePrincipalWorkerPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalWorkerPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServicePrincipalWorkerPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalWorkerPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalWorkerPermissionUpdate) check() error {
	if _u.mutation.ServicePrincipalCleared() && len(_u.mutation.ServicePrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalWorkerPermission.service_principal"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalWorkerPermission.permission"`)
	}
	return nil
}

func (_u *ServicePrincipalWorkerPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipalworkerpermission.Table, serviceprincipalworkerpermission.Columns, sqlgraph.NewFieldSpec(serviceprincipalworkerpermission.FieldServicePrincipalID, field.TypeInt64), sqlgraph.NewFieldSpec(serviceprincipalworkerpermission.FieldPermissionID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.ServicePrincipalTable,
			Columns: []string{serviceprincipalworkerpermission.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.ServicePrincipalTable,
			Columns: []string{serviceprincipalworkerpermission.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.PermissionTable,
			Columns: []string{serviceprincipalworkerpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.PermissionTable,
			Columns: []string{serviceprincipalworkerpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipalworkerpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServicePrincipalWorkerPermissionUpdateOne is the builder for updating a single ServicePrincipalWorkerPermission entity.
type ServicePrincipalWorkerPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServicePrincipalWorkerPermissionMutation
}

// SetServicePrincipalID sets the "service_principal_id" field.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetServicePrincipalID(v int64) *ServicePrincipalWorkerPermissionUpdateOne {
	_u.mutation.SetServicePrincipalID(v)
	return _u
}

// SetNillableServicePrincipalID sets the "service_principal_id" field if the given value is not nil.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetNillableServicePrincipalID(v *int64) *ServicePrincipalWorkerPermissionUpdateOne {
	if v != nil {
		_u.SetServicePrincipalID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetPermissionID(v int64) *ServicePrincipalWorkerPermissionUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetNillablePermissionID(v *int64) *ServicePrincipalWorkerPermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetServicePrincipal sets the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetServicePrincipal(v *ServicePrincipal) *ServicePrincipalWorkerPermissionUpdateOne {
	return _u.SetServicePrincipalID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SetPermission(v *Permission) *ServicePrincipalWorkerPermissionUpdateOne {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the ServicePrincipalWorkerPermissionMutation object of the builder.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) Mutation() *ServicePrincipalWorkerPermissionMutation {
	return _u.mutation
}

// ClearServicePrincipal clears the "service_principal" edge to the ServicePrincipal entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) ClearServicePrincipal() *ServicePrincipalWorkerPermissionUpdateOne {
	_u.mutation.ClearServicePrincipal()
	return _u
}

// ClearPermission clears the "permission" edge to the Permission entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) ClearPermission() *ServicePrincipalWorkerPermissionUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// Where appends a list predicates to the ServicePrincipalWorkerPermissionUpdate builder.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) Where(ps ...predicate.ServicePrincipalWorkerPermission) *ServicePrincipalWorkerPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) Select(field string, fields ...string) *ServicePrincipalWorkerPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServicePrincipalWorkerPermission entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) Save(ctx context.Context) (*ServicePrincipalWorkerPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) SaveX(ctx context.Context) *ServicePrincipalWorkerPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServicePrincipalWorkerPermissionUpdateOne) check() error {
	if _u.mutation.ServicePrincipalCleared() && len(_u.mutation.ServicePrincipalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalWorkerPermission.service_principal"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServicePrincipalWorkerPermission.permission"`)
	}
	return nil
}

func (_u *ServicePrincipalWorkerPermissionUpdateOne) sqlSave(ctx context.Context) (_node *ServicePrincipalWorkerPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceprincipalworkerpermission.Table, serviceprincipalworkerpermission.Columns, sqlgraph.NewFieldSpec(serviceprincipalworkerpermission.FieldServicePrincipalID, field.TypeInt64), sqlgraph.NewFieldSpec(serviceprincipalworkerpermission.FieldPermissionID, field.TypeInt64))
	if id, ok := _u.mutation.ServicePrincipalID(); !ok {
		return nil, &ValidationError{Name: "service_principal_id", err: errors.New(`ent: missing "ServicePrincipalWorkerPermission.service_principal_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.PermissionID(); !ok {
		return nil, &ValidationError{Name: "permission_id", err: errors.New(`ent: missing "ServicePrincipalWorkerPermission.permission_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !serviceprincipalworkerpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ServicePrincipalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.ServicePrincipalTable,
			Columns: []string{serviceprincipalworkerpermission.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicePrincipalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.ServicePrincipalTable,
			Columns: []string{serviceprincipalworkerpermission.ServicePrincipalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serviceprincipal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.PermissionTable,
			Columns: []string{serviceprincipalworkerpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   serviceprincipalworkerpermission.PermissionTable,
			Columns: []string{serviceprincipalworkerpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ServicePrincipalWorkerPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceprincipalworkerpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
