// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userhostingentitlement"
)

// UserHostingEntitlement is the model entity for the UserHostingEntitlement schema.
type UserHostingEntitlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AccountLimit holds the value of the "account_limit" field.
	AccountLimit int64 `json:"account_limit,omitempty"`
	// GroupLimit holds the value of the "group_limit" field.
	GroupLimit int64 `json:"group_limit,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID int64 `json:"created_by_user_id,omitempty"`
	// UpdatedByUserID holds the value of the "updated_by_user_id" field.
	UpdatedByUserID int64 `json:"updated_by_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserHostingEntitlementQuery when eager-loading is set.
	Edges        UserHostingEntitlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserHostingEntitlementEdges holds the relations/edges for other nodes in the graph.
type UserHostingEntitlementEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the updated_by edge.
	UpdatedBy *User `json:"updated_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserHostingEntitlementEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserHostingEntitlementEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// UpdatedByOrErr returns the UpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserHostingEntitlementEdges) UpdatedByOrErr() (*User, error) {
	if e.UpdatedBy != nil {
		return e.UpdatedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updated_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserHostingEntitlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userhostingentitlement.FieldID, userhostingentitlement.FieldUserID, userhostingentitlement.FieldAccountLimit, userhostingentitlement.FieldGroupLimit, userhostingentitlement.FieldVersion, userhostingentitlement.FieldCreatedByUserID, userhostingentitlement.FieldUpdatedByUserID:
			values[i] = new(sql.NullInt64)
		case userhostingentitlement.FieldCreatedAt, userhostingentitlement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserHostingEntitlement fields.
func (_m *UserHostingEntitlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userhostingentitlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userhostingentitlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userhostingentitlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userhostingentitlement.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userhostingentitlement.FieldAccountLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_limit", values[i])
			} else if value.Valid {
				_m.AccountLimit = value.Int64
			}
		case userhostingentitlement.FieldGroupLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_limit", values[i])
			} else if value.Valid {
				_m.GroupLimit = value.Int64
			}
		case userhostingentitlement.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case userhostingentitlement.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = value.Int64
			}
		case userhostingentitlement.FieldUpdatedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by_user_id", values[i])
			} else if value.Valid {
				_m.UpdatedByUserID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserHostingEntitlement.
// This includes values selected through modifiers, order, etc.
func (_m *UserHostingEntitlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserHostingEntitlement entity.
func (_m *UserHostingEntitlement) QueryUser() *UserQuery {
	return NewUserHostingEntitlementClient(_m.config).QueryUser(_m)
}

// QueryCreatedBy queries the "created_by" edge of the UserHostingEntitlement entity.
func (_m *UserHostingEntitlement) QueryCreatedBy() *UserQuery {
	return NewUserHostingEntitlementClient(_m.config).QueryCreatedBy(_m)
}

// QueryUpdatedBy queries the "updated_by" edge of the UserHostingEntitlement entity.
func (_m *UserHostingEntitlement) QueryUpdatedBy() *UserQuery {
	return NewUserHostingEntitlementClient(_m.config).QueryUpdatedBy(_m)
}

// Update returns a builder for updating this UserHostingEntitlement.
// Note that you need to call UserHostingEntitlement.Unwrap() before calling this method if this UserHostingEntitlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserHostingEntitlement) Update() *UserHostingEntitlementUpdateOne {
	return NewUserHostingEntitlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserHostingEntitlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserHostingEntitlement) Unwrap() *UserHostingEntitlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserHostingEntitlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserHostingEntitlement) String() string {
	var builder strings.Builder
	builder.WriteString("UserHostingEntitlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("account_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountLimit))
	builder.WriteString(", ")
	builder.WriteString("group_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupLimit))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByUserID))
	builder.WriteString(", ")
	builder.WriteString("updated_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedByUserID))
	builder.WriteByte(')')
	return builder.String()
}

// UserHostingEntitlements is a parsable slice of UserHostingEntitlement.
type UserHostingEntitlements []*UserHostingEntitlement
