// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userhostingentitlement"
)

// UserHostingEntitlementCreate is the builder for creating a UserHostingEntitlement entity.
type UserHostingEntitlementCreate struct {
	config
	mutation *UserHostingEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserHostingEntitlementCreate) SetCreatedAt(v time.Time) *UserHostingEntitlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserHostingEntitlementCreate) SetNillableCreatedAt(v *time.Time) *UserHostingEntitlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserHostingEntitlementCreate) SetUpdatedAt(v time.Time) *UserHostingEntitlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserHostingEntitlementCreate) SetNillableUpdatedAt(v *time.Time) *UserHostingEntitlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserHostingEntitlementCreate) SetUserID(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountLimit sets the "account_limit" field.
func (_c *UserHostingEntitlementCreate) SetAccountLimit(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetAccountLimit(v)
	return _c
}

// SetNillableAccountLimit sets the "account_limit" field if the given value is not nil.
func (_c *UserHostingEntitlementCreate) SetNillableAccountLimit(v *int64) *UserHostingEntitlementCreate {
	if v != nil {
		_c.SetAccountLimit(*v)
	}
	return _c
}

// SetGroupLimit sets the "group_limit" field.
func (_c *UserHostingEntitlementCreate) SetGroupLimit(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetGroupLimit(v)
	return _c
}

// SetNillableGroupLimit sets the "group_limit" field if the given value is not nil.
func (_c *UserHostingEntitlementCreate) SetNillableGroupLimit(v *int64) *UserHostingEntitlementCreate {
	if v != nil {
		_c.SetGroupLimit(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *UserHostingEntitlementCreate) SetVersion(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *UserHostingEntitlementCreate) SetNillableVersion(v *int64) *UserHostingEntitlementCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *UserHostingEntitlementCreate) SetCreatedByUserID(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (_c *UserHostingEntitlementCreate) SetUpdatedByUserID(v int64) *UserHostingEntitlementCreate {
	_c.mutation.SetUpdatedByUserID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserHostingEntitlementCreate) SetUser(v *User) *UserHostingEntitlementCreate {
	return _c.SetUserID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *UserHostingEntitlementCreate) SetCreatedByID(id int64) *UserHostingEntitlementCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *UserHostingEntitlementCreate) SetCreatedBy(v *User) *UserHostingEntitlementCreate {
	return _c.SetCreatedByID(v.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (_c *UserHostingEntitlementCreate) SetUpdatedByID(id int64) *UserHostingEntitlementCreate {
	_c.mutation.SetUpdatedByID(id)
	return _c
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (_c *UserHostingEntitlementCreate) SetUpdatedBy(v *User) *UserHostingEntitlementCreate {
	return _c.SetUpdatedByID(v.ID)
}

// Mutation returns the UserHostingEntitlementMutation object of the builder.
func (_c *UserHostingEntitlementCreate) Mutation() *UserHostingEntitlementMutation {
	return _c.mutation
}

// Save creates the UserHostingEntitlement in the database.
func (_c *UserHostingEntitlementCreate) Save(ctx context.Context) (*UserHostingEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserHostingEntitlementCreate) SaveX(ctx context.Context) *UserHostingEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserHostingEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserHostingEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserHostingEntitlementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userhostingentitlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userhostingentitlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AccountLimit(); !ok {
		v := userhostingentitlement.DefaultAccountLimit
		_c.mutation.SetAccountLimit(v)
	}
	if _, ok := _c.mutation.GroupLimit(); !ok {
		v := userhostingentitlement.DefaultGroupLimit
		_c.mutation.SetGroupLimit(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := userhostingentitlement.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserHostingEntitlementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserHostingEntitlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserHostingEntitlement.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserHostingEntitlement.user_id"`)}
	}
	if _, ok := _c.mutation.AccountLimit(); !ok {
		return &ValidationError{Name: "account_limit", err: errors.New(`ent: missing required field "UserHostingEntitlement.account_limit"`)}
	}
	if v, ok := _c.mutation.AccountLimit(); ok {
		if err := userhostingentitlement.AccountLimitValidator(v); err != nil {
			return &ValidationError{Name: "account_limit", err: fmt.Errorf(`ent: validator failed for field "UserHostingEntitlement.account_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupLimit(); !ok {
		return &ValidationError{Name: "group_limit", err: errors.New(`ent: missing required field "UserHostingEntitlement.group_limit"`)}
	}
	if v, ok := _c.mutation.GroupLimit(); ok {
		if err := userhostingentitlement.GroupLimitValidator(v); err != nil {
			return &ValidationError{Name: "group_limit", err: fmt.Errorf(`ent: validator failed for field "UserHostingEntitlement.group_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "UserHostingEntitlement.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := userhostingentitlement.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "UserHostingEntitlement.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "UserHostingEntitlement.created_by_user_id"`)}
	}
	if _, ok := _c.mutation.UpdatedByUserID(); !ok {
		return &ValidationError{Name: "updated_by_user_id", err: errors.New(`ent: missing required field "UserHostingEntitlement.updated_by_user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserHostingEntitlement.user"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "UserHostingEntitlement.created_by"`)}
	}
	if len(_c.mutation.UpdatedByIDs()) == 0 {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required edge "UserHostingEntitlement.updated_by"`)}
	}
	return nil
}

func (_c *UserHostingEntitlementCreate) sqlSave(ctx context.Context) (*UserHostingEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserHostingEntitlementCreate) createSpec() (*UserHostingEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &UserHostingEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userhostingentitlement.Table, sqlgraph.NewFieldSpec(userhostingentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userhostingentitlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userhostingentitlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountLimit(); ok {
		_spec.SetField(userhostingentitlement.FieldAccountLimit, field.TypeInt64, value)
		_node.AccountLimit = value
	}
	if value, ok := _c.mutation.GroupLimit(); ok {
		_spec.SetField(userhostingentitlement.FieldGroupLimit, field.TypeInt64, value)
		_node.GroupLimit = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(userhostingentitlement.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userhostingentitlement.UserTable,
			Columns: []string{userhostingentitlement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userhostingentitlement.CreatedByTable,
			Columns: []string{userhostingentitlement.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userhostingentitlement.UpdatedByTable,
			Columns: []string{userhostingentitlement.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpdatedByUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserHostingEntitlement.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserHostingEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserHostingEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *UserHostingEntitlementUpsertOne {
	_c.conflict = opts
	return &UserHostingEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserHostingEntitlementCreate) OnConflictColumns(columns ...string) *UserHostingEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserHostingEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// UserHostingEntitlementUpsertOne is the builder for "upsert"-ing
	//  one UserHostingEntitlement node.
	UserHostingEntitlementUpsertOne struct {
		create *UserHostingEntitlementCreate
	}

	// UserHostingEntitlementUpsert is the "OnConflict" setter.
	UserHostingEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserHostingEntitlementUpsert) SetUpdatedAt(v time.Time) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateUpdatedAt() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserHostingEntitlementUpsert) SetUserID(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateUserID() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldUserID)
	return u
}

// SetAccountLimit sets the "account_limit" field.
func (u *UserHostingEntitlementUpsert) SetAccountLimit(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldAccountLimit, v)
	return u
}

// UpdateAccountLimit sets the "account_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateAccountLimit() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldAccountLimit)
	return u
}

// AddAccountLimit adds v to the "account_limit" field.
func (u *UserHostingEntitlementUpsert) AddAccountLimit(v int64) *UserHostingEntitlementUpsert {
	u.Add(userhostingentitlement.FieldAccountLimit, v)
	return u
}

// SetGroupLimit sets the "group_limit" field.
func (u *UserHostingEntitlementUpsert) SetGroupLimit(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldGroupLimit, v)
	return u
}

// UpdateGroupLimit sets the "group_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateGroupLimit() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldGroupLimit)
	return u
}

// AddGroupLimit adds v to the "group_limit" field.
func (u *UserHostingEntitlementUpsert) AddGroupLimit(v int64) *UserHostingEntitlementUpsert {
	u.Add(userhostingentitlement.FieldGroupLimit, v)
	return u
}

// SetVersion sets the "version" field.
func (u *UserHostingEntitlementUpsert) SetVersion(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateVersion() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *UserHostingEntitlementUpsert) AddVersion(v int64) *UserHostingEntitlementUpsert {
	u.Add(userhostingentitlement.FieldVersion, v)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *UserHostingEntitlementUpsert) SetCreatedByUserID(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateCreatedByUserID() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldCreatedByUserID)
	return u
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (u *UserHostingEntitlementUpsert) SetUpdatedByUserID(v int64) *UserHostingEntitlementUpsert {
	u.Set(userhostingentitlement.FieldUpdatedByUserID, v)
	return u
}

// UpdateUpdatedByUserID sets the "updated_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsert) UpdateUpdatedByUserID() *UserHostingEntitlementUpsert {
	u.SetExcluded(userhostingentitlement.FieldUpdatedByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserHostingEntitlementUpsertOne) UpdateNewValues() *UserHostingEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userhostingentitlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserHostingEntitlementUpsertOne) Ignore() *UserHostingEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserHostingEntitlementUpsertOne) DoNothing() *UserHostingEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserHostingEntitlementCreate.OnConflict
// documentation for more info.
func (u *UserHostingEntitlementUpsertOne) Update(set func(*UserHostingEntitlementUpsert)) *UserHostingEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserHostingEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserHostingEntitlementUpsertOne) SetUpdatedAt(v time.Time) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateUpdatedAt() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserHostingEntitlementUpsertOne) SetUserID(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateUserID() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountLimit sets the "account_limit" field.
func (u *UserHostingEntitlementUpsertOne) SetAccountLimit(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetAccountLimit(v)
	})
}

// AddAccountLimit adds v to the "account_limit" field.
func (u *UserHostingEntitlementUpsertOne) AddAccountLimit(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddAccountLimit(v)
	})
}

// UpdateAccountLimit sets the "account_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateAccountLimit() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateAccountLimit()
	})
}

// SetGroupLimit sets the "group_limit" field.
func (u *UserHostingEntitlementUpsertOne) SetGroupLimit(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetGroupLimit(v)
	})
}

// AddGroupLimit adds v to the "group_limit" field.
func (u *UserHostingEntitlementUpsertOne) AddGroupLimit(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddGroupLimit(v)
	})
}

// UpdateGroupLimit sets the "group_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateGroupLimit() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateGroupLimit()
	})
}

// SetVersion sets the "version" field.
func (u *UserHostingEntitlementUpsertOne) SetVersion(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserHostingEntitlementUpsertOne) AddVersion(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateVersion() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateVersion()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *UserHostingEntitlementUpsertOne) SetCreatedByUserID(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateCreatedByUserID() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (u *UserHostingEntitlementUpsertOne) SetUpdatedByUserID(v int64) *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUpdatedByUserID(v)
	})
}

// UpdateUpdatedByUserID sets the "updated_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertOne) UpdateUpdatedByUserID() *UserHostingEntitlementUpsertOne {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUpdatedByUserID()
	})
}

// Exec executes the query.
func (u *UserHostingEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserHostingEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserHostingEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserHostingEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserHostingEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserHostingEntitlementCreateBulk is the builder for creating many UserHostingEntitlement entities in bulk.
type UserHostingEntitlementCreateBulk struct {
	config
	err      error
	builders []*UserHostingEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the UserHostingEntitlement entities in the database.
func (_c *UserHostingEntitlementCreateBulk) Save(ctx context.Context) ([]*UserHostingEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserHostingEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserHostingEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserHostingEntitlementCreateBulk) SaveX(ctx context.Context) []*UserHostingEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserHostingEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserHostingEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserHostingEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserHostingEntitlementUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserHostingEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserHostingEntitlementUpsertBulk {
	_c.conflict = opts
	return &UserHostingEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserHostingEntitlementCreateBulk) OnConflictColumns(columns ...string) *UserHostingEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserHostingEntitlementUpsertBulk{
		create: _c,
	}
}

// UserHostingEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of UserHostingEntitlement nodes.
type UserHostingEntitlementUpsertBulk struct {
	create *UserHostingEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserHostingEntitlementUpsertBulk) UpdateNewValues() *UserHostingEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userhostingentitlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserHostingEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserHostingEntitlementUpsertBulk) Ignore() *UserHostingEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserHostingEntitlementUpsertBulk) DoNothing() *UserHostingEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserHostingEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *UserHostingEntitlementUpsertBulk) Update(set func(*UserHostingEntitlementUpsert)) *UserHostingEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserHostingEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserHostingEntitlementUpsertBulk) SetUpdatedAt(v time.Time) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateUpdatedAt() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserHostingEntitlementUpsertBulk) SetUserID(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateUserID() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountLimit sets the "account_limit" field.
func (u *UserHostingEntitlementUpsertBulk) SetAccountLimit(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetAccountLimit(v)
	})
}

// AddAccountLimit adds v to the "account_limit" field.
func (u *UserHostingEntitlementUpsertBulk) AddAccountLimit(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddAccountLimit(v)
	})
}

// UpdateAccountLimit sets the "account_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateAccountLimit() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateAccountLimit()
	})
}

// SetGroupLimit sets the "group_limit" field.
func (u *UserHostingEntitlementUpsertBulk) SetGroupLimit(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetGroupLimit(v)
	})
}

// AddGroupLimit adds v to the "group_limit" field.
func (u *UserHostingEntitlementUpsertBulk) AddGroupLimit(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddGroupLimit(v)
	})
}

// UpdateGroupLimit sets the "group_limit" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateGroupLimit() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateGroupLimit()
	})
}

// SetVersion sets the "version" field.
func (u *UserHostingEntitlementUpsertBulk) SetVersion(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserHostingEntitlementUpsertBulk) AddVersion(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateVersion() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateVersion()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *UserHostingEntitlementUpsertBulk) SetCreatedByUserID(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateCreatedByUserID() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (u *UserHostingEntitlementUpsertBulk) SetUpdatedByUserID(v int64) *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.SetUpdatedByUserID(v)
	})
}

// UpdateUpdatedByUserID sets the "updated_by_user_id" field to the value that was provided on create.
func (u *UserHostingEntitlementUpsertBulk) UpdateUpdatedByUserID() *UserHostingEntitlementUpsertBulk {
	return u.Update(func(s *UserHostingEntitlementUpsert) {
		s.UpdateUpdatedByUserID()
	})
}

// Exec executes the query.
func (u *UserHostingEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserHostingEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserHostingEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserHostingEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
