// Code generated by ent, DO NOT EDIT.

package userrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUserID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldRoleID, v))
}

// GrantedByUserID applies equality check predicate on the "granted_by_user_id" field. It's identical to GrantedByUserIDEQ.
func GrantedByUserID(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedByServicePrincipalID applies equality check predicate on the "granted_by_service_principal_id" field. It's identical to GrantedByServicePrincipalIDEQ.
func GrantedByServicePrincipalID(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldGrantedByServicePrincipalID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldRoleID, vs...))
}

// GrantedByUserIDEQ applies the EQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDNEQ applies the NEQ predicate on the "granted_by_user_id" field.
func GrantedByUserIDNEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldGrantedByUserID, v))
}

// GrantedByUserIDIn applies the In predicate on the "granted_by_user_id" field.
func GrantedByUserIDIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDNotIn applies the NotIn predicate on the "granted_by_user_id" field.
func GrantedByUserIDNotIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldGrantedByUserID, vs...))
}

// GrantedByUserIDIsNil applies the IsNil predicate on the "granted_by_user_id" field.
func GrantedByUserIDIsNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldIsNull(FieldGrantedByUserID))
}

// GrantedByUserIDNotNil applies the NotNil predicate on the "granted_by_user_id" field.
func GrantedByUserIDNotNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldNotNull(FieldGrantedByUserID))
}

// GrantedByServicePrincipalIDEQ applies the EQ predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldGrantedByServicePrincipalID, v))
}

// GrantedByServicePrincipalIDNEQ applies the NEQ predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNEQ(v int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldGrantedByServicePrincipalID, v))
}

// GrantedByServicePrincipalIDIn applies the In predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldGrantedByServicePrincipalID, vs...))
}

// GrantedByServicePrincipalIDNotIn applies the NotIn predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNotIn(vs ...int64) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldGrantedByServicePrincipalID, vs...))
}

// GrantedByServicePrincipalIDIsNil applies the IsNil predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDIsNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldIsNull(FieldGrantedByServicePrincipalID))
}

// GrantedByServicePrincipalIDNotNil applies the NotNil predicate on the "granted_by_service_principal_id" field.
func GrantedByServicePrincipalIDNotNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldNotNull(FieldGrantedByServicePrincipalID))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserRole {
	return predicate.UserRole(sql.FieldNotNull(FieldExpiresAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantedByUser applies the HasEdge predicate on the "granted_by_user" edge.
func HasGrantedByUser() predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GrantedByUserTable, GrantedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedByUserWith applies the HasEdge predicate on the "granted_by_user" edge with a given conditions (other predicates).
func HasGrantedByUserWith(preds ...predicate.User) predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := newGrantedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantedByServicePrincipal applies the HasEdge predicate on the "granted_by_service_principal" edge.
func HasGrantedByServicePrincipal() predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GrantedByServicePrincipalTable, GrantedByServicePrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedByServicePrincipalWith applies the HasEdge predicate on the "granted_by_service_principal" edge with a given conditions (other predicates).
func HasGrantedByServicePrincipalWith(preds ...predicate.ServicePrincipal) predicate.UserRole {
	return predicate.UserRole(func(s *sql.Selector) {
		step := newGrantedByServicePrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.NotPredicates(p))
}
