// Code generated by ent, DO NOT EDIT.

package resourceauthorizationevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the resourceauthorizationevent type in the database.
	Label = "resource_authorization_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldActorServicePrincipalID holds the string denoting the actor_service_principal_id field in the database.
	FieldActorServicePrincipalID = "actor_service_principal_id"
	// FieldResourceOwnerUserID holds the string denoting the resource_owner_user_id field in the database.
	FieldResourceOwnerUserID = "resource_owner_user_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldResourceAccessVersion holds the string denoting the resource_access_version field in the database.
	FieldResourceAccessVersion = "resource_access_version"
	// FieldAuthMethod holds the string denoting the auth_method field in the database.
	FieldAuthMethod = "auth_method"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeActorUser holds the string denoting the actor_user edge name in mutations.
	EdgeActorUser = "actor_user"
	// EdgeActorServicePrincipal holds the string denoting the actor_service_principal edge name in mutations.
	EdgeActorServicePrincipal = "actor_service_principal"
	// EdgeResourceOwner holds the string denoting the resource_owner edge name in mutations.
	EdgeResourceOwner = "resource_owner"
	// Table holds the table name of the resourceauthorizationevent in the database.
	Table = "resource_authorization_events"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "resource_authorization_events"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "resource_authorization_events"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// ActorUserTable is the table that holds the actor_user relation/edge.
	ActorUserTable = "resource_authorization_events"
	// ActorUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ActorUserInverseTable = "users"
	// ActorUserColumn is the table column denoting the actor_user relation/edge.
	ActorUserColumn = "actor_user_id"
	// ActorServicePrincipalTable is the table that holds the actor_service_principal relation/edge.
	ActorServicePrincipalTable = "resource_authorization_events"
	// ActorServicePrincipalInverseTable is the table name for the ServicePrincipal entity.
	// It exists in this package in order to avoid circular dependency with the "serviceprincipal" package.
	ActorServicePrincipalInverseTable = "service_principals"
	// ActorServicePrincipalColumn is the table column denoting the actor_service_principal relation/edge.
	ActorServicePrincipalColumn = "actor_service_principal_id"
	// ResourceOwnerTable is the table that holds the resource_owner relation/edge.
	ResourceOwnerTable = "resource_authorization_events"
	// ResourceOwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ResourceOwnerInverseTable = "users"
	// ResourceOwnerColumn is the table column denoting the resource_owner relation/edge.
	ResourceOwnerColumn = "resource_owner_user_id"
)

// Columns holds all SQL columns for resourceauthorizationevent fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldGroupID,
	FieldActorUserID,
	FieldActorServicePrincipalID,
	FieldResourceOwnerUserID,
	FieldEventType,
	FieldResourceAccessVersion,
	FieldAuthMethod,
	FieldRequestID,
	FieldDetails,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultAuthMethod holds the default value on creation for the "auth_method" field.
	DefaultAuthMethod string
	// AuthMethodValidator is a validator for the "auth_method" field. It is called by the builders before save.
	AuthMethodValidator func(string) error
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultDetails holds the default value on creation for the "details" field.
	DefaultDetails func() map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ResourceAuthorizationEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByActorServicePrincipalID orders the results by the actor_service_principal_id field.
func ByActorServicePrincipalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorServicePrincipalID, opts...).ToFunc()
}

// ByResourceOwnerUserID orders the results by the resource_owner_user_id field.
func ByResourceOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceOwnerUserID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByResourceAccessVersion orders the results by the resource_access_version field.
func ByResourceAccessVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceAccessVersion, opts...).ToFunc()
}

// ByAuthMethod orders the results by the auth_method field.
func ByAuthMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMethod, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByActorUserField orders the results by actor_user field.
func ByActorUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByActorServicePrincipalField orders the results by actor_service_principal field.
func ByActorServicePrincipalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorServicePrincipalStep(), sql.OrderByField(field, opts...))
	}
}

// ByResourceOwnerField orders the results by resource_owner field.
func ByResourceOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newActorUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActorUserTable, ActorUserColumn),
	)
}
func newActorServicePrincipalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorServicePrincipalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ActorServicePrincipalTable, ActorServicePrincipalColumn),
	)
}
func newResourceOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceOwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ResourceOwnerTable, ResourceOwnerColumn),
	)
}
