// Code generated by ent, DO NOT EDIT.

package resourceauthorizationevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldGroupID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldActorUserID, v))
}

// ActorServicePrincipalID applies equality check predicate on the "actor_service_principal_id" field. It's identical to ActorServicePrincipalIDEQ.
func ActorServicePrincipalID(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldActorServicePrincipalID, v))
}

// ResourceOwnerUserID applies equality check predicate on the "resource_owner_user_id" field. It's identical to ResourceOwnerUserIDEQ.
func ResourceOwnerUserID(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldResourceOwnerUserID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldEventType, v))
}

// ResourceAccessVersion applies equality check predicate on the "resource_access_version" field. It's identical to ResourceAccessVersionEQ.
func ResourceAccessVersion(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldResourceAccessVersion, v))
}

// AuthMethod applies equality check predicate on the "auth_method" field. It's identical to AuthMethodEQ.
func AuthMethod(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldAuthMethod, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldRequestID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotNull(FieldAccountID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotNull(FieldGroupID))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotNull(FieldActorUserID))
}

// ActorServicePrincipalIDEQ applies the EQ predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldActorServicePrincipalID, v))
}

// ActorServicePrincipalIDNEQ applies the NEQ predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldActorServicePrincipalID, v))
}

// ActorServicePrincipalIDIn applies the In predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldActorServicePrincipalID, vs...))
}

// ActorServicePrincipalIDNotIn applies the NotIn predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldActorServicePrincipalID, vs...))
}

// ActorServicePrincipalIDIsNil applies the IsNil predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDIsNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIsNull(FieldActorServicePrincipalID))
}

// ActorServicePrincipalIDNotNil applies the NotNil predicate on the "actor_service_principal_id" field.
func ActorServicePrincipalIDNotNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotNull(FieldActorServicePrincipalID))
}

// ResourceOwnerUserIDEQ applies the EQ predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldResourceOwnerUserID, v))
}

// ResourceOwnerUserIDNEQ applies the NEQ predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldResourceOwnerUserID, v))
}

// ResourceOwnerUserIDIn applies the In predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldResourceOwnerUserID, vs...))
}

// ResourceOwnerUserIDNotIn applies the NotIn predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldResourceOwnerUserID, vs...))
}

// ResourceOwnerUserIDIsNil applies the IsNil predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDIsNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIsNull(FieldResourceOwnerUserID))
}

// ResourceOwnerUserIDNotNil applies the NotNil predicate on the "resource_owner_user_id" field.
func ResourceOwnerUserIDNotNil() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotNull(FieldResourceOwnerUserID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContainsFold(FieldEventType, v))
}

// ResourceAccessVersionEQ applies the EQ predicate on the "resource_access_version" field.
func ResourceAccessVersionEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldResourceAccessVersion, v))
}

// ResourceAccessVersionNEQ applies the NEQ predicate on the "resource_access_version" field.
func ResourceAccessVersionNEQ(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldResourceAccessVersion, v))
}

// ResourceAccessVersionIn applies the In predicate on the "resource_access_version" field.
func ResourceAccessVersionIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldResourceAccessVersion, vs...))
}

// ResourceAccessVersionNotIn applies the NotIn predicate on the "resource_access_version" field.
func ResourceAccessVersionNotIn(vs ...int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldResourceAccessVersion, vs...))
}

// ResourceAccessVersionGT applies the GT predicate on the "resource_access_version" field.
func ResourceAccessVersionGT(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldResourceAccessVersion, v))
}

// ResourceAccessVersionGTE applies the GTE predicate on the "resource_access_version" field.
func ResourceAccessVersionGTE(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldResourceAccessVersion, v))
}

// ResourceAccessVersionLT applies the LT predicate on the "resource_access_version" field.
func ResourceAccessVersionLT(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldResourceAccessVersion, v))
}

// ResourceAccessVersionLTE applies the LTE predicate on the "resource_access_version" field.
func ResourceAccessVersionLTE(v int64) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldResourceAccessVersion, v))
}

// AuthMethodEQ applies the EQ predicate on the "auth_method" field.
func AuthMethodEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldAuthMethod, v))
}

// AuthMethodNEQ applies the NEQ predicate on the "auth_method" field.
func AuthMethodNEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldAuthMethod, v))
}

// AuthMethodIn applies the In predicate on the "auth_method" field.
func AuthMethodIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldAuthMethod, vs...))
}

// AuthMethodNotIn applies the NotIn predicate on the "auth_method" field.
func AuthMethodNotIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldAuthMethod, vs...))
}

// AuthMethodGT applies the GT predicate on the "auth_method" field.
func AuthMethodGT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldAuthMethod, v))
}

// AuthMethodGTE applies the GTE predicate on the "auth_method" field.
func AuthMethodGTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldAuthMethod, v))
}

// AuthMethodLT applies the LT predicate on the "auth_method" field.
func AuthMethodLT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldAuthMethod, v))
}

// AuthMethodLTE applies the LTE predicate on the "auth_method" field.
func AuthMethodLTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldAuthMethod, v))
}

// AuthMethodContains applies the Contains predicate on the "auth_method" field.
func AuthMethodContains(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContains(FieldAuthMethod, v))
}

// AuthMethodHasPrefix applies the HasPrefix predicate on the "auth_method" field.
func AuthMethodHasPrefix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasPrefix(FieldAuthMethod, v))
}

// AuthMethodHasSuffix applies the HasSuffix predicate on the "auth_method" field.
func AuthMethodHasSuffix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasSuffix(FieldAuthMethod, v))
}

// AuthMethodEqualFold applies the EqualFold predicate on the "auth_method" field.
func AuthMethodEqualFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEqualFold(FieldAuthMethod, v))
}

// AuthMethodContainsFold applies the ContainsFold predicate on the "auth_method" field.
func AuthMethodContainsFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContainsFold(FieldAuthMethod, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldContainsFold(FieldRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActorUser applies the HasEdge predicate on the "actor_user" edge.
func HasActorUser() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActorUserTable, ActorUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorUserWith applies the HasEdge predicate on the "actor_user" edge with a given conditions (other predicates).
func HasActorUserWith(preds ...predicate.User) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := newActorUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActorServicePrincipal applies the HasEdge predicate on the "actor_service_principal" edge.
func HasActorServicePrincipal() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActorServicePrincipalTable, ActorServicePrincipalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorServicePrincipalWith applies the HasEdge predicate on the "actor_service_principal" edge with a given conditions (other predicates).
func HasActorServicePrincipalWith(preds ...predicate.ServicePrincipal) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := newActorServicePrincipalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResourceOwner applies the HasEdge predicate on the "resource_owner" edge.
func HasResourceOwner() predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ResourceOwnerTable, ResourceOwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceOwnerWith applies the HasEdge predicate on the "resource_owner" edge with a given conditions (other predicates).
func HasResourceOwnerWith(preds ...predicate.User) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(func(s *sql.Selector) {
		step := newResourceOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourceAuthorizationEvent) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourceAuthorizationEvent) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourceAuthorizationEvent) predicate.ResourceAuthorizationEvent {
	return predicate.ResourceAuthorizationEvent(sql.NotPredicates(p))
}
